# Load the list of Russell 2000 tickers and company names
russell2000_data = [
    ("AAMI", "Acadian Asset Management Inc."),
    ("AAOI", "APPLIED OPTOELECTRONICS, INC."),
    ("AAT", "American Assets Trust, Inc."),
    ("ABCB", "Ameris Bancorp"),
    ("ABG", "ASBURY AUTOMOTIVE GROUP INC"),
    ("ABM", "ABM INDUSTRIES INC /DE/"),
    ("ABOS", "Acumen Pharmaceuticals, Inc."),
    ("ABR", "ARBOR REALTY TRUST INC"),
    ("ABSI", "Absci Corp"),
    ("ABUS", "Arbutus Biopharma Corp"),
    ("ACA", "Arcosa, Inc."),
    ("ACAD", "ACADIA PHARMACEUTICALS INC"),
    ("ACCD", "Accolade, Inc."),
    ("ACCO", "ACCO BRANDS Corp"),
    ("ACDC", "ProFrac Holding Corp."),
    ("ACEL", "Accel Entertainment, Inc."),
    ("ACHR", "Archer Aviation Inc."),
    ("ACHV", "ACHIEVE LIFE SCIENCES, INC."),
    ("ACIC", "AMERICAN COASTAL INSURANCE Corp"),
    ("ACIW", "ACI WORLDWIDE, INC."),
    ("ACLS", "AXCELIS TECHNOLOGIES INC"),
    ("ACLX", "Arcellx, Inc."),
    ("ACMR", "ACM Research, Inc."),
    ("ACNB", "ACNB CORP"),
    ("ACRE", "Ares Commercial Real Estate Corp"),
    ("ACRV", "Acrivon Therapeutics, Inc."),
    ("ACT", "Enact Holdings, Inc."),
    ("ACTG", "ACACIA RESEARCH CORP"),
    ("ACVA", "ACV Auctions Inc."),
    ("ADCT", "ADC Therapeutics SA"),
    ("ADEA", "Adeia Inc."),
    ("ADMA", "ADMA BIOLOGICS, INC."),
    ("ADNT", "Adient plc"),
    ("ADPT", "Adaptive Biotechnologies Corp"),
    ("ADRO", ""),
    ("ADTN", "ADTRAN Holdings, Inc."),
    ("ADUS", "Addus HomeCare Corp"),
    ("ADV", "Advantage Solutions Inc."),
    ("ADVM", "Adverum Biotechnologies, Inc."),
    ("AEHR", "AEHR TEST SYSTEMS"),
    ("AEIS", "ADVANCED ENERGY INDUSTRIES INC"),
    ("AEO", "AMERICAN EAGLE OUTFITTERS INC"),
    ("AESI", "Atlas Energy Solutions Inc."),
    ("AEVA", "Aeva Technologies, Inc."),
    ("AEYE", "AUDIOEYE INC"),
    ("AFCG", "Advanced Flower Capital Inc."),
    ("AFRI", "Forafric Global PLC"),
    ("AGEN", "AGENUS INC"),
    ("AGIO", "AGIOS PHARMACEUTICALS, INC."),
    ("AGL", "agilon health, inc."),
    ("AGM", "FEDERAL AGRICULTURAL MORTGAGE CORP"),
    ("AGS", "PlayAGS, Inc."),
    ("AGX", "ARGAN INC"),
    ("AGYS", "AGILYSYS INC"),
    ("AHCO", "AdaptHealth Corp."),
    ("AHH", "Armada Hoffler Properties, Inc."),
    ("AHR", "American Healthcare REIT, Inc."),
    ("AI", "C3.ai, Inc."),
    ("AIN", "ALBANY INTERNATIONAL CORP /DE/"),
    ("AIOT", "PowerFleet Inc."),
    ("AIP", "Arteris, Inc."),
    ("AIR", "AAR CORP"),
    ("AIRS", "Airsculpt Technologies, Inc."),
    ("AISP", "Airship AI Holdings, Inc."),
    ("AIT", "APPLIED INDUSTRIAL TECHNOLOGIES INC"),
    ("AIV", "APARTMENT INVESTMENT & MANAGEMENT CO"),
    ("AKBA", "Akebia Therapeutics, Inc."),
    ("AKR", "ACADIA REALTY TRUST"),
    ("AKRO", "Akero Therapeutics, Inc."),
    ("AKYA", "Akoya Biosciences, Inc."),
    ("ALCO", "ALICO, INC."),
    ("ALDX", "Aldeyra Therapeutics, Inc."),
    ("ALE", "ALLETE INC"),
    ("ALEC", "Alector, Inc."),
    ("ALEX", "Alexander & Baldwin, Inc."),
    ("ALG", "ALAMO GROUP INC"),
    ("ALGT", "Allegiant Travel CO"),
    ("ALHC", "Alignment Healthcare, Inc."),
    ("ALIT", "Alight, Inc. / Delaware"),
    ("ALKS", "Alkermes plc."),
    ("ALKT", "ALKAMI TECHNOLOGY, INC."),
    ("ALLO", "Allogene Therapeutics, Inc."),
    ("ALMS", "ALUMIS INC."),
    ("ALNT", "ALLIENT INC"),
    ("ALRM", "Alarm.com Holdings, Inc."),
    ("ALRS", "ALERUS FINANCIAL CORP"),
    ("ALT", "Altimmune, Inc."),
    ("ALTG", "ALTA EQUIPMENT GROUP INC."),
    ("ALTI", "AlTi Global, Inc."),
    ("ALX", "ALEXANDERS INC"),
    ("ALXO", "ALX ONCOLOGY HOLDINGS INC"),
    ("AMAL", "Amalgamated Financial Corp."),
    ("AMBA", "AMBARELLA INC"),
    ("AMBC", "AMBAC FINANCIAL GROUP INC"),
    ("AMBP", "Ardagh Metal Packaging S.A."),
    ("AMC", "AMC ENTERTAINMENT HOLDINGS, INC."),
    ("AMCX", "AMC Networks Inc."),
    ("AMN", "AMN HEALTHCARE SERVICES INC"),
    ("AMPH", "Amphastar Pharmaceuticals, Inc."),
    ("AMPL", "Amplitude, Inc."),
    ("AMPS", "Altus Power, Inc."),
    ("AMPX", "Amprius Technologies, Inc."),
    ("AMPY", "Amplify Energy Corp."),
    ("AMR", "Alpha Metallurgical Resources, Inc."),
    ("AMRC", "Ameresco, Inc."),
    ("AMRK", "A-Mark Precious Metals, Inc."),
    ("AMRX", "Amneal Pharmaceuticals, Inc."),
    ("AMSC", "AMERICAN SUPERCONDUCTOR CORP /DE/"),
    ("AMSF", "AMERISAFE INC"),
    ("AMTB", "Amerant Bancorp Inc."),
    ("AMTX", "AEMETIS, INC"),
    ("AMWD", "AMERICAN WOODMARK CORP"),
    ("ANAB", "ANAPTYSBIO, INC"),
    ("ANDE", "Andersons, Inc."),
    ("ANF", "ABERCROMBIE & FITCH CO /DE/"),
    ("ANGO", "ANGIODYNAMICS INC"),
    ("ANIK", "Anika Therapeutics, Inc."),
    ("ANIP", "ANI PHARMACEUTICALS INC"),
    ("ANNX", "Annexon, Inc."),
    ("ANRO", "Alto Neuroscience, Inc."),
    ("AOMR", "Angel Oak Mortgage REIT, Inc."),
    ("AORT", "ARTIVION, INC."),
    ("AOSL", "ALPHA & OMEGA SEMICONDUCTOR Ltd"),
    ("APAM", "Artisan Partners Asset Management Inc."),
    ("APEI", "AMERICAN PUBLIC EDUCATION INC"),
    ("APGE", "Apogee Therapeutics, Inc."),
    ("APLD", "Applied Digital Corp."),
    ("APLE", "Apple Hospitality REIT, Inc."),
    ("APLT", "Applied Therapeutics, Inc."),
    ("APOG", "APOGEE ENTERPRISES, INC."),
    ("APPN", "APPIAN CORP"),
    ("APPS", "Digital Turbine, Inc."),
    ("AQST", "Aquestive Therapeutics, Inc."),
    ("ARAY", "ACCURAY INC"),
    ("ARCB", "ARCBEST CORP /DE/"),
    ("ARCT", "Arcturus Therapeutics Holdings Inc."),
    ("ARDT", "Ardent Health Partners, Inc."),
    ("ARDX", "ARDELYX, INC."),
    ("ARHS", "Arhaus, Inc."),
    ("ARI", "Apollo Commercial Real Estate Finance, Inc."),
    ("ARIS", "Aris Water Solutions, Inc."),
    ("ARKO", "ARKO Corp."),
    ("ARL", "AMERICAN REALTY INVESTORS INC"),
    ("ARLO", "Arlo Technologies, Inc."),
    ("AROC", "Archrock, Inc."),
    ("AROW", "ARROW FINANCIAL CORP"),
    ("ARQ", "Arq, Inc."),
    ("ARQT", "Arcutis Biotherapeutics, Inc."),
    ("ARR", "Armour Residential REIT, Inc."),
    ("ARRY", "Array Technologies, Inc."),
    ("ARTV", "Artiva Biotherapeutics, Inc."),
    ("ARVN", "ARVINAS, INC."),
    ("ARWR", "ARROWHEAD PHARMACEUTICALS, INC."),
    ("ASAN", "Asana, Inc."),
    ("ASB", "ASSOCIATED BANC-CORP"),
    ("ASC", "Ardmore Shipping Corp"),
    ("ASGN", "ASGN Inc"),
    ("ASIX", "AdvanSix Inc."),
    ("ASLE", "AerSale Corp"),
    ("ASO", "Academy Sports & Outdoors, Inc."),
    ("ASPI", "ASP Isotopes Inc."),
    ("ASPN", "ASPEN AEROGELS INC"),
    ("ASTE", "ASTEC INDUSTRIES INC"),
    ("ASTH", "Astrana Health, Inc."),
    ("ASTS", "AST SpaceMobile, Inc."),
    ("ASUR", "ASURE SOFTWARE INC"),
    ("ATEC", "Alphatec Holdings, Inc."),
    ("ATEN", "A10 Networks, Inc."),
    ("ATEX", "Anterix Inc."),
    ("ATGE", "Adtalem Global Education Inc."),
    ("ATKR", "Atkore Inc."),
    ("ATLC", "Atlanticus Holdings Corp"),
    ("ATLO", "AMES NATIONAL CORP"),
    ("ATMU", "Atmus Filtration Technologies Inc."),
    ("ATNI", "ATN International, Inc."),
    ("ATNM", "Actinium Pharmaceuticals, Inc."),
    ("ATOS", "ATOSSA THERAPEUTICS, INC."),
    ("ATRC", "AtriCure, Inc."),
    ("ATRO", "ASTRONICS CORP"),
    ("ATSG", "Air Transport Services Group, Inc."),
    ("ATXS", "Astria Therapeutics, Inc."),
    ("AUB", "Atlantic Union Bankshares Corp"),
    ("AUPH", "Aurinia Pharmaceuticals Inc."),
    ("AUR", "Aurora Innovation, Inc."),
    ("AURA", "Aura Biosciences, Inc."),
    ("AVA", "AVISTA CORP"),
    ("AVAH", "Aveanna Healthcare Holdings, Inc."),
    ("AVAV", "AeroVironment Inc"),
    ("AVBP", "Arrivent Biopharma Inc."),
    ("AVD", "AMERICAN VANGUARD CORP"),
    ("AVDL", "AVADEL PHARMACEUTICALS PLC"),
    ("AVDX", "AvidXchange Holdings, Inc."),
    ("AVIR", "Atea Pharmaceuticals, Inc."),
    ("AVNS", "AVANOS MEDICAL, INC."),
    ("AVNT", "AVIENT CORP"),
    ("AVNW", "AVIAT NETWORKS, INC."),
    ("AVO", "Mission Produce, Inc."),
    ("AVPT", "AvePoint, Inc."),
    ("AVTE", "Aerovate Therapeutics, Inc."),
    ("AVXL", "ANAVEX LIFE SCIENCES CORP."),
    ("AWR", "AMERICAN STATES WATER CO"),
    ("AX", "Axos Financial, Inc."),
    ("AXGN", "Axogen, Inc."),
    ("AXL", "AMERICAN AXLE & MANUFACTURING HOLDINGS INC"),
    ("AXSM", "Axsome Therapeutics, Inc."),
    ("AZZ", "AZZ INC"),
    ("BANC", "BANC OF CALIFORNIA, INC."),
    ("BAND", "Bandwidth Inc."),
    ("BANF", "BANCFIRST CORP /OK/"),
    ("BANR", "BANNER CORP"),
    ("BARK", "Bark, Inc."),
    ("BASE", "Couchbase, Inc."),
    ("BATRA", "Atlanta Braves Holdings, Inc."),
    ("BATRK", "Atlanta Braves Holdings, Inc."),
    ("BBAI", "BigBear.ai Holdings, Inc."),
    ("BBCP", "Concrete Pumping Holdings, Inc."),
    ("BBIO", "BridgeBio Pharma, Inc."),
    ("BBNX", "Beta Bionics, Inc."),
    ("BBSI", "BARRETT BUSINESS SERVICES INC"),
    ("BBUC", "Brookfield Business Corp"),
    ("BBW", "BUILD-A-BEAR WORKSHOP INC"),
    ("BCAL", "California BanCorp CA"),
    ("BCAX", "Bicara Therapeutics Inc."),
    ("BCBP", "BCB BANCORP INC"),
    ("BCC", "BOISE CASCADE Co"),
    ("BCML", "BayCom Corp"),
    ("BCO", "BRINKS CO"),
    ("BCPC", "BALCHEM CORP"),
    ("BCRX", "BIOCRYST PHARMACEUTICALS INC"),
    ("BDC", "BELDEN INC."),
    ("BDN", "BRANDYWINE REALTY TRUST"),
    ("BDTX", "Black Diamond Therapeutics, Inc."),
    ("BE", "Bloom Energy Corp"),
    ("BEAM", "Beam Therapeutics Inc."),
    ("BECN", "BEACON ROOFING SUPPLY INC"),
    ("BELFA", "BEL FUSE INC /NJ"),
    ("BELFB", "BEL FUSE INC /NJ"),
    ("BFC", "Bank First Corp"),
    ("BFH", "BREAD FINANCIAL HOLDINGS, INC."),
    ("BFS", "SAUL CENTERS, INC."),
    ("BFST", "Business First Bancshares, Inc."),
    ("BGC", "BGC Group, Inc."),
    ("BGS", "B&G Foods, Inc."),
    ("BH", "Biglari Holdings Inc."),
    ("BHB", "BAR HARBOR BANKSHARES"),
    ("BHE", "BENCHMARK ELECTRONICS INC"),
    ("BHLB", "BERKSHIRE HILLS BANCORP INC"),
    ("BHR", "Braemar Hotels & Resorts Inc."),
    ("BHRB", "Burke & Herbert Financial Services Corp."),
    ("BHVN", "Biohaven Ltd."),
    ("BIGC", "BigCommerce Holdings, Inc."),
    ("BIOA", "BioAge Labs, Inc."),
    ("BIPC", "Brookfield Infrastructure Corp"),
    ("BJRI", "BJs RESTAURANTS INC"),
    ("BKD", "Brookdale Senior Living Inc."),
    ("BKE", "BUCKLE INC"),
    ("BKH", "BLACK HILLS CORP /SD/"),
    ("BKSY", "BlackSky Technology Inc."),
    ("BKU", "BankUnited, Inc."),
    ("BKV", "BKV Corp"),
    ("BL", "BLACKLINE, INC."),
    ("BLBD", "Blue Bird Corp"),
    ("BLDE", "Blade Air Mobility, Inc."),
    ("BLFS", "BIOLIFE SOLUTIONS INC"),
    ("BLFY", "Blue Foundry Bancorp"),
    ("BLKB", "BLACKBAUD INC"),
    ("BLMN", "Bloomin' Brands, Inc."),
    ("BLND", "Blend Labs, Inc."),
    ("BLNK", "Blink Charging Co."),
    ("BLUE", "bluebird bio, Inc."),
    ("BLX", "FOREIGN TRADE BANK OF LATIN AMERICA, INC."),
    ("BLZE", "Backblaze, Inc."),
    ("BMBL", "Bumble Inc."),
    ("BMEA", "Biomea Fusion, Inc."),
    ("BMI", "BADGER METER INC"),
    ("BMRC", "Bank of Marin Bancorp"),
    ("BNL", "Broadstone Net Lease, Inc."),
    ("BOC", "BOSTON OMAHA Corp"),
    ("BOH", "BANK OF HAWAII CORP"),
    ("BOLD", "Boundless Bio, Inc."),
    ("BOOM", "DMC Global Inc."),
    ("BOOT", "Boot Barn Holdings, Inc."),
    ("BORR", "Borr Drilling Ltd"),
    ("BOW", "Bowhead Specialty Holdings Inc."),
    ("BOX", "BOX INC"),
    ("BPMC", "Blueprint Medicines Corp"),
    ("BPRN", "Princeton Bancorp, Inc."),
    ("BRCC", "BRC Inc."),
    ("BRKL", "BROOKLINE BANCORP INC"),
    ("BRSP", "BrightSpire Capital, Inc."),
    ("BRT", "BRT Apartments Corp."),
    ("BRY", "Berry Corp (bry)"),
    ("BRZE", "Braze, Inc."),
    ("BSRR", "SIERRA BANCORP"),
    ("BSVN", "Bank7 Corp."),
    ("BTBT", "Bit Digital, Inc"),
    ("BTMD", "biote Corp."),
    ("BTSG", "BrightSpring Health Services, Inc."),
    ("BTU", "PEABODY ENERGY CORP"),
    ("BUR", "Burford Capital Ltd"),
    ("BUSE", "FIRST BUSEY CORP /NV/"),
    ("BV", "BrightView Holdings, Inc."),
    ("BVS", "Bioventus Inc."),
    ("BWB", "Bridgewater Bancshares Inc"),
    ("BWFG", "Bankwell Financial Group, Inc."),
    ("BWIN", "Baldwin Insurance Group, Inc."),
    ("BWMN", "Bowman Consulting Group Ltd."),
    ("BXC", "BlueLinx Holdings Inc."),
    ("BXMT", "BLACKSTONE MORTGAGE TRUST, INC."),
    ("BY", "BYLINE BANCORP, INC."),
    ("BYND", "BEYOND MEAT, INC."),
    ("BYON", "BEYOND, INC."),
    ("BYRN", "Byrna Technologies Inc."),
    ("BZH", "BEAZER HOMES USA INC"),
    ("CABA", "Cabaletta Bio, Inc."),
    ("CABO", "Cable One, Inc."),
    ("CAC", "CAMDEN NATIONAL CORP"),
    ("CADE", "Cadence Bank"),
    ("CADL", "Candel Therapeutics, Inc."),
    ("CAKE", "The Cheesecake Factory Incorporated"),
    ("CAL", "CALERES INC"),
    ("CALM", "CAL-MAINE FOODS INC"),
    ("CALX", "CALIX, INC"),
    ("CAMP", "Camp4 Therapeutics Corp"),
    ("CAPR", "CAPRICOR THERAPEUTICS, INC."),
    ("CARE", "Carter Bankshares, Inc."),
    ("CARG", "CarGurus, Inc."),
    ("CARS", "Cars.com Inc."),
    ("CASH", "PATHWARD FINANCIAL, INC."),
    ("CASS", "CASS INFORMATION SYSTEMS INC"),
    ("CATX", "Perspective Therapeutics, Inc."),
    ("CATY", "CATHAY GENERAL BANCORP"),
    ("CBAN", "COLONY BANKCORP INC"),
    ("CBL", "CBL & ASSOCIATES PROPERTIES INC"),
    ("CBLL", "Ceribell, Inc."),
    ("CBNK", "Capital Bancorp Inc"),
    ("CBRL", "CRACKER BARREL OLD COUNTRY STORE, INC"),
    ("CBT", "CABOT CORP"),
    ("CBU", "COMMUNITY FINANCIAL SYSTEM, INC."),
    ("CBUS", "Cibus, Inc."),
    ("CBZ", "CBIZ, Inc."),
    ("CCB", "COASTAL FINANCIAL CORP"),
    ("CCBG", "CAPITAL CITY BANK GROUP INC"),
    ("CCCC", "C4 Therapeutics, Inc."),
    ("CCNE", "CNB FINANCIAL CORP/PA"),
    ("CCO", "Clear Channel Outdoor Holdings, Inc."),
    ("CCOI", "COGENT COMMUNICATIONS HOLDINGS, INC."),
    ("CCRN", "CROSS COUNTRY HEALTHCARE INC"),
    ("CCS", "Century Communities, Inc."),
    ("CCSI", "Consensus Cloud Solutions, Inc."),
    ("CDE", "Coeur Mining, Inc."),
    ("CDLX", "Cardlytics, Inc."),
    ("CDNA", "CareDx, Inc."),
    ("CDP", "COPT DEFENSE PROPERTIES"),
    ("CDRE", "Cadre Holdings, Inc."),
    ("CDXS", "CODEXIS, INC."),
    ("CDZI", "CADIZ INC"),
    ("CECO", "CECO ENVIRONMENTAL CORP"),
    ("CELC", "Celcuity Inc."),
    ("CENT", "CENTRAL GARDEN & PET CO"),
    ("CENTA", "CENTRAL GARDEN & PET CO"),
    ("CENX", "CENTURY ALUMINUM CO"),
    ("CERS", "CERUS CORP"),
    ("CEVA", "CEVA INC"),
    ("CFFN", "Capitol Federal Financial, Inc."),
    ("CGEM", "Cullinan Therapeutics, Inc."),
    ("CGON", "Cg Oncology, Inc."),
    ("CHCO", "CITY HOLDING CO"),
    ("CHCT", "Community Healthcare Trust Inc"),
    ("CHEF", "Chefs' Warehouse, Inc."),
    ("CHGG", "CHEGG, INC"),
    ("CHMG", "CHEMUNG FINANCIAL CORP"),
    ("CHPT", "ChargePoint Holdings, Inc."),
    ("CHRS", "Coherus BioSciences, Inc."),
    ("CHX", "ChampionX Corp"),
    ("CIFR", "Cipher Mining Inc."),
    ("CIM", "CHIMERA INVESTMENT CORP"),
    ("CIO", "City Office REIT, Inc."),
    ("CIVB", "CIVISTA BANCSHARES, INC."),
    ("CIX", "COMPX INTERNATIONAL INC"),
    ("CLAR", "Clarus Corp"),
    ("CLB", "Core Laboratories Inc."),
    ("CLBK", "Columbia Financial, Inc."),
    ("CLDT", "Chatham Lodging Trust"),
    ("CLDX", "Celldex Therapeutics, Inc."),
    ("CLFD", "Clearfield, Inc."),
    ("CLMB", "Climb Global Solutions, Inc."),
    ("CLNE", "Clean Energy Fuels Corp."),
    ("CLPR", "Clipper Realty Inc."),
    ("CLSKW", "Cleanspark Inc."),
    ("CLW", "Clearwater Paper Corp"),
    ("CLYM", "Climb Bio, Inc."),
    ("CMC", "COMMERCIAL METALS Co"),
    ("CMCL", "Caledonia Mining Corp Plc"),
    ("CMCO", "COLUMBUS MCKINNON CORP"),
    ("CMP", "COMPASS MINERALS INTERNATIONAL INC"),
    ("CMPO", "CompoSecure, Inc."),
    ("CMPR", "CIMPRESS plc"),
    ("CMPX", "Compass Therapeutics, Inc."),
    ("CMRE", "Costamare Inc."),
    ("CMT", "CORE MOLDING TECHNOLOGIES INC"),
    ("CMTG", "Claros Mortgage Trust, Inc."),
    ("CNDT", "CONDUENT Inc"),
    ("CNK", "Cinemark Holdings, Inc."),
    ("CNMD", "CONMED Corp"),
    ("CNNE", "Cannae Holdings, Inc."),
    ("CNO", "CNO Financial Group, Inc."),
    ("CNOB", "ConnectOne Bancorp, Inc."),
    ("CNR", "Core Natural Resources, Inc."),
    ("CNS", "COHEN & STEERS, INC."),
    ("CNX", "CNX Resources Corp"),
    ("CNXN", "PC CONNECTION INC"),
    ("COCO", "Vita Coco Company, Inc."),
    ("CODI", "Compass Diversified Holdings"),
    ("COFS", "CHOICEONE FINANCIAL SERVICES INC"),
    ("COGT", "Cogent Biosciences, Inc."),
    ("COHU", "COHU INC"),
    ("COLL", "COLLEGIUM PHARMACEUTICAL, INC"),
    ("COMM", "CommScope Holding Company, Inc."),
    ("COMP", "Compass, Inc."),
    ("CON", "Concentra Group Holdings Parent, Inc."),
    ("COOK", "Traeger, Inc."),
    ("COOP", "Mr. Cooper Group Inc."),
    ("CORT", "CORCEPT THERAPEUTICS INC"),
    ("CORZ", "Core Scientific, Inc./tx"),
    ("COUR", "Coursera, Inc."),
    ("CPF", "CENTRAL PACIFIC FINANCIAL CORP"),
    ("CPK", "CHESAPEAKE UTILITIES CORP"),
    ("CPRX", "CATALYST PHARMACEUTICALS, INC."),
    ("CPS", "Cooper-Standard Holdings Inc."),
    ("CPSS", "CONSUMER PORTFOLIO SERVICES, INC."),
    ("CRAI", "CRA INTERNATIONAL, INC."),
    ("CRBP", "Corbus Pharmaceuticals Holdings, Inc."),
    ("CRBU", "Caribou Biosciences, Inc."),
    ("CRC", "California Resources Corp"),
    ("CRCT", "Cricut, Inc."),
    ("CRDA", "Croda International Plc"),
    ("CRDF", "Cardiff Oncology, Inc."),
    ("CRDO", "Credo Technology Group Holding Ltd"),
    ("CRGX", "CARGO Therapeutics, Inc."),
    ("CRGY", "Crescent Energy Co"),
    ("CRK", "COMSTOCK RESOURCES INC"),
    ("CRMD", "CorMedix Inc."),
    ("CRMT", "AMERICAS CARMART INC"),
    ("CRNC", "Cerence Inc."),
    ("CRNX", "Crinetics Pharmaceuticals, Inc."),
    ("CRS", "CARPENTER TECHNOLOGY CORP"),
    ("CRSR", "Corsair Gaming, Inc."),
    ("CRVL", "CORVEL CORP"),
    ("CRVO", "CervoMed Inc."),
    ("CSGS", "CSG SYSTEMS INTERNATIONAL INC"),
    ("CSR", "CENTERSPACE"),
    ("CSTE", "Caesarstone Ltd."),
    ("CSTL", "CASTLE BIOSCIENCES INC"),
    ("CSTM", "CONSTELLIUM SE"),
    ("CSV", "CARRIAGE SERVICES INC"),
    ("CSWI", "CSW INDUSTRIALS, INC."),
    ("CTBI", "COMMUNITY TRUST BANCORP INC /KY/"),
    ("CTGO", "Contango ORE, Inc."),
    ("CTKB", "Cytek Biosciences, Inc."),
    ("CTLP", "CANTALOUPE, INC."),
    ("CTNM", "Contineum Therapeutics, Inc."),
    ("CTO", "CTO Realty Growth, Inc."),
    ("CTOS", "Custom Truck One Source, Inc."),
    ("CTRE", "CareTrust REIT, Inc."),
    ("CTRI", "Centuri Holdings, Inc."),
    ("CTRN", "Citi Trends Inc"),
    ("CTS", "CTS CORP"),
    ("CUBI", "Customers Bancorp, Inc."),
    ("CURB", "Curbline Properties Corp."),
    ("CURV", "Torrid Holdings Inc."),
    ("CVBF", "CVB FINANCIAL CORP"),
    ("CVCO", "CAVCO INDUSTRIES INC."),
    ("CVGI", "Commercial Vehicle Group, Inc."),
    ("CVGW", "CALAVO GROWERS INC"),
    ("CVI", "CVR ENERGY INC"),
    ("CVLG", "COVENANT LOGISTICS GROUP, INC."),
    ("CVLT", "COMMVAULT SYSTEMS INC"),
    ("CVRX", "CVRx, Inc."),
    ("CWAN", "Clearwater Analytics Holdings, Inc."),
    ("CWBC", "Community West Bancshares"),
    ("CWCO", "Consolidated Water Co. Ltd."),
    ("CWH", "Camping World Holdings, Inc."),
    ("CWK", "Cushman & Wakefield plc"),
    ("CWST", "CASELLA WASTE SYSTEMS INC"),
    ("CWT", "CALIFORNIA WATER SERVICE GROUP"),
    ("CXM", "Sprinklr, Inc."),
    ("CXW", "CoreCivic, Inc."),
    ("CYH", "COMMUNITY HEALTH SYSTEMS INC"),
    ("CYRX", "Cryoport, Inc."),
    ("CYTK", "CYTOKINETICS INC"),
    ("CZFS", "CITIZENS FINANCIAL SERVICES INC"),
    ("CZNC", "CITIZENS & NORTHERN CORP"),
    ("DAKT", "DAKTRONICS INC /SD/"),
    ("DAN", "DANA INC"),
    ("DAVE", "Dave Inc./DE"),
    ("DAWN", "Day One Biopharmaceuticals, Inc."),
    ("DBD", "Diebold Nixdorf Inc."),
    ("DBI", "Designer Brands Inc."),
    ("DBRG", "DigitalBridge Group, Inc."),
    ("DC", "Dakota Gold Corp."),
    ("DCGO", "DocGo Inc."),
    ("DCO", "DUCOMMUN INC /DE/"),
    ("DCOM", "Dime Community Bancshares, Inc. /NY/"),
    ("DDD", "3D SYSTEMS CORP"),
    ("DEA", "Easterly Government Properties, Inc."),
    ("DEC", "Diversified Energy Co PLC"),
    ("DEI", "Douglas Emmett Inc"),
    ("DENN", "DENNY'S Corp"),
    ("DESP", "Despegar.com, Corp."),
    ("DFH", "Dream Finders Homes, Inc."),
    ("DFIN", "Donnelley Financial Solutions, Inc."),
    ("DGICA", "DONEGAL GROUP INC"),
    ("DGII", "DIGI INTERNATIONAL INC"),
    ("DH", "Definitive Healthcare Corp."),
    ("DHC", "DIVERSIFIED HEALTHCARE TRUST"),
    ("DHIL", "DIAMOND HILL INVESTMENT GROUP INC"),
    ("DHT", "DHT Holdings, Inc."),
    ("DIBS", "1stdibs.com, Inc."),
    ("DIN", "Dine Brands Global, Inc."),
    ("DIOD", "DIODES INC /DEL/"),
    ("DJCO", "DAILY JOURNAL CORP"),
    ("DK", "Delek US Holdings, Inc."),
    ("DLHC", "DLH Holdings Corp."),
    ("DLX", "DELUXE CORP"),
    ("DMRC", "Digimarc CORP"),
    ("DNLI", "Denali Therapeutics Inc."),
    ("DNOW", "DNOW Inc."),
    ("DNTH", "Dianthus Therapeutics, Inc. /DE/"),
    ("DNUT", "Krispy Kreme, Inc."),
    ("DOCN", "DigitalOcean Holdings, Inc."),
    ("DOLE", "Dole plc"),
    ("DOMO", "DOMO, INC."),
    ("DORM", "Dorman Products, Inc."),
    ("DRH", "DiamondRock Hospitality Co"),
    ("DRS", "Leonardo DRS, Inc."),
    ("DRVN", "Driven Brands Holdings Inc."),
    ("DSGN", "Design Therapeutics, Inc."),
    ("DSGR", "Distribution Solutions Group, Inc."),
    ("DSP", "Viant Technology Inc."),
    ("DTC", "Solo Brands Inc."),
    ("DTI", "Drilling Tools International Corp"),
    ("DVAX", "DYNAVAX TECHNOLOGIES CORP"),
    ("DX", "DYNEX CAPITAL INC"),
    ("DXLG", "DESTINATION XL GROUP, INC."),
    ("DXPE", "DXP ENTERPRISES INC"),
    ("DY", "DYCOM INDUSTRIES INC"),
    ("DYN", "Dyne Therapeutics, Inc."),
    ("EAF", "GRAFTECH INTERNATIONAL LTD"),
    ("EAT", "BRINKER INTERNATIONAL, INC"),
    ("EB", "Eventbrite, Inc."),
    ("EBC", "Eastern Bankshares, Inc."),
    ("EBF", "ENNIS, INC."),
    ("EBTC", "ENTERPRISE BANCORP INC /MA/"),
    ("ECPG", "ENCORE CAPITAL GROUP INC"),
    ("ECVT", "Ecovyst Inc."),
    ("EDIT", "Editas Medicine, Inc."),
    ("EE", "Excelerate Energy, Inc."),
    ("EEX", "Emerald Holding, Inc."),
    ("EFC", "Ellington Financial Inc."),
    ("EFSC", "ENTERPRISE FINANCIAL SERVICES CORP"),
    ("EGAN", "EGAIN Corp"),
    ("EGBN", "EAGLE BANCORP INC"),
    ("EGHT", "8X8 INC /DE/"),
    ("EGY", "VAALCO ENERGY INC /DE/"),
    ("EHAB", "Enhabit, Inc."),
    ("EIG", "Employers Holdings, Inc."),
    ("ELEV", "Elevation Oncology, Inc."),
    ("ELME", "Elme Communities"),
    ("ELVN", "Enliven Therapeutics, Inc."),
    ("EMBC", "Embecta Corp."),
    ("EML", "EASTERN CO"),
    ("ENFN", "Enfusion, Inc."),
    ("ENR", "ENERGIZER HOLDINGS, INC."),
    ("ENS", "EnerSys"),
    ("ENSG", "ENSIGN GROUP, INC"),
    ("ENTA", "ENANTA PHARMACEUTICALS INC"),
    ("ENVA", "Enova International, Inc."),
    ("ENVX", "Enovix Corp"),
    ("EOLS", "Evolus, Inc."),
    ("EP", "EMPIRE PETROLEUM CORP"),
    ("EPAC", "ENERPAC TOOL GROUP CORP"),
    ("EPC", "EDGEWELL PERSONAL CARE Co"),
    ("EPM", "EVOLUTION PETROLEUM CORP"),
    ("EPRT", "ESSENTIAL PROPERTIES REALTY TRUST, INC."),
    ("EQBK", "EQUITY BANCSHARES INC"),
    ("ERAS", "Erasca, Inc."),
    ("ERII", "Energy Recovery, Inc."),
    ("ESCA", "ESCALADE INC"),
    ("ESE", "ESCO TECHNOLOGIES INC"),
    ("ESGR", "Enstar Group LTD"),
    ("ESNT", "Essent Group Ltd."),
    ("ESPR", "Esperion Therapeutics, Inc."),
    ("ESQ", "Esquire Financial Holdings, Inc."),
    ("ESRT", "Empire State Realty Trust, Inc."),
    ("ESSA", "ESSA Bancorp, Inc."),
    ("ETD", "ETHAN ALLEN INTERIORS INC"),
    ("ETNB", "89bio, Inc."),
    ("ETWO", "E2open Parent Holdings, Inc."),
    ("EU", "enCore Energy Corp."),
    ("EVC", "ENTRAVISION COMMUNICATIONS CORP"),
    ("EVCM", "EverCommerce Inc."),
    ("EVER", "EverQuote, Inc."),
    ("EVEX", "Eve Holding, Inc."),
    ("EVGO", "EVgo Inc."),
    ("EVH", "Evolent Health, Inc."),
    ("EVI", "EVI INDUSTRIES, INC."),
    ("EVLV", "Evolv Technologies Holdings, Inc."),
    ("EVRI", "Everi Holdings Inc."),
    ("EVTC", "EVERTEC, Inc."),
    ("EWCZ", "European Wax Center, Inc."),
    ("EWTX", "Edgewise Therapeutics, Inc."),
    ("EXLS", "ExlService Holdings, Inc."),
    ("EXPI", "EXP World Holdings, Inc."),
    ("EXPO", "EXPONENT INC"),
    ("EXTR", "EXTREME NETWORKS INC"),
    ("EYE", "National Vision Holdings, Inc."),
    ("EYPT", "EyePoint Pharmaceuticals, Inc."),
    ("FA", "FIRST ADVANTAGE CORP"),
    ("FARO", "FARO TECHNOLOGIES INC"),
    ("FATE", "FATE THERAPEUTICS INC"),
    ("FBIZ", "FIRST BUSINESS FINANCIAL SERVICES, INC."),
    ("FBK", "FB Financial Corp"),
    ("FBLG", "FibroBiologics, Inc."),
    ("FBNC", "FIRST BANCORP /NC/"),
    ("FBP", "FIRST BANCORP /PR/"),
    ("FBRT", "Franklin BSP Realty Trust, Inc."),
    ("FC", "FRANKLIN COVEY CO"),
    ("FCBC", "FIRST COMMUNITY BANKSHARES INC /VA/"),
    ("FCEL", "FUELCELL ENERGY INC"),
    ("FCF", "FIRST COMMONWEALTH FINANCIAL CORP /PA/"),
    ("FCFS", "FirstCash Holdings, Inc."),
    ("FCPT", "Four Corners Property Trust, Inc."),
    ("FDBC", "FIDELITY D & D BANCORP INC"),
    ("FDMT", "4D Molecular Therapeutics, Inc."),
    ("FDP", "FRESH DEL MONTE PRODUCE INC"),
    ("FELE", "FRANKLIN ELECTRIC CO INC"),
    ("FENC", "FENNEC PHARMACEUTICALS INC."),
    ("FET", "FORUM ENERGY TECHNOLOGIES, INC."),
    ("FF", "FutureFuel Corp."),
    ("FFBC", "FIRST FINANCIAL BANCORP /OH/"),
    ("FFIC", "FLUSHING FINANCIAL CORP"),
    ("FFIN", "FIRST FINANCIAL BANKSHARES INC"),
    ("FFNW", "First Financial Northwest, Inc."),
    ("FFWM", "First Foundation Inc."),
    ("FG", "F&G Annuities & Life, Inc."),
    ("FHTX", "Foghorn Therapeutics Inc."),
    ("FIBK", "FIRST INTERSTATE BANCSYSTEM INC"),
    ("FIGS", "FIGS, Inc."),
    ("FIHL", "Fidelis Insurance Holdings Ltd"),
    ("FIP", "FTAI Infrastructure Inc."),
    ("FISI", "FINANCIAL INSTITUTIONS INC"),
    ("FIZZ", "NATIONAL BEVERAGE CORP"),
    ("FL", "FOOT LOCKER, INC."),
    ("FLG", "FLAGSTAR FINANCIAL, INC."),
    ("FLGT", "Fulgent Genetics, Inc."),
    ("FLIC", "FIRST OF LONG ISLAND CORP"),
    ("FLL", "FULL HOUSE RESORTS INC"),
    ("FLNC", "Fluence Energy, Inc."),
    ("FLNG", "Flex LNG Ltd."),
    ("FLOC", "Flowco Holdings Inc."),
    ("FLR", "FLUOR CORP"),
    ("FLWS", "1 800 FLOWERS COM INC"),
    ("FLXS", "FLEXSTEEL INDUSTRIES INC"),
    ("FLYW", "Flywire Corp"),
    ("FMAO", "FARMERS & MERCHANTS BANCORP INC"),
    ("FMBH", "FIRST MID BANCSHARES, INC."),
    ("FMNB", "FARMERS NATIONAL BANC CORP /OH/"),
    ("FN", "Fabrinet"),
    ("FNA", "Paragon 28 Inc."),
    ("FNKO", "Funko, Inc."),
    ("FNLC", "First Bancorp, Inc /ME/"),
    ("FOLD", "AMICUS THERAPEUTICS, INC."),
    ("FOR", "Forestar Group Inc."),
    ("FORM", "FORMFACTOR INC"),
    ("FORR", "FORRESTER RESEARCH, INC."),
    ("FOXF", "FOX FACTORY HOLDING CORP"),
    ("FPI", "Farmland Partners Inc."),
    ("FRBA", "First Bank"),
    ("FRGE", "Forge Global Holdings, Inc."),
    ("FRME", "FIRST MERCHANTS CORP"),
    ("FRPH", "FRP HOLDINGS, INC."),
    ("FRSH", "Freshworks Inc."),
    ("FRST", "Primis Financial Corp."),
    ("FSBC", "FIVE STAR BANCORP"),
    ("FSBW", "FS Bancorp, Inc."),
    ("FSLY", "Fastly, Inc."),
    ("FSP", "FRANKLIN STREET PROPERTIES CORP /MA/"),
    ("FSS", "FEDERAL SIGNAL CORP /DE/"),
    ("FSTR", "FOSTER L B CO"),
    ("FTAI", "FTAI Aviation Ltd."),
    ("FTDR", "Frontdoor, Inc."),
    ("FUBO", "fuboTV Inc. /FL"),
    ("FUL", "FULLER H B CO"),
    ("FULC", "Fulcrum Therapeutics, Inc."),
    ("FULT", "FULTON FINANCIAL CORP"),
    ("FUN", "Six Flags Entertainment Corporation/NEW"),
    ("FVCB", "FVCBankcorp, Inc."),
    ("FVR", "FrontView REIT, Inc."),
    ("FWRD", "FORWARD AIR CORP"),
    ("FWRG", "First Watch Restaurant Group, Inc."),
    ("GABC", "GERMAN AMERICAN BANCORP, INC."),
    ("GALT", "GALECTIN THERAPEUTICS INC"),
    ("GAMB", "Gambling.com Group Ltd"),
    ("GATX", "GATX CORP"),
    ("GBCI", "GLACIER BANCORP, INC."),
    ("GBIO", "Generation Bio Co."),
    ("GBTG", "Global Business Travel Group, Inc."),
    ("GBX", "GREENBRIER COMPANIES INC"),
    ("GCBC", "GREENE COUNTY BANCORP INC"),
    ("GCI", "Gannett Co., Inc."),
    ("GCMG", "GCM Grosvenor Inc."),
    ("GCO", "GENESCO INC"),
    ("GCT", "GigaCloud Technology Inc"),
    ("GCTS", "GCT Semiconductor Holding, Inc."),
    ("GDEN", "GOLDEN ENTERTAINMENT, INC."),
    ("GDOT", "GREEN DOT CORP"),
    ("GDYN", "GRID DYNAMICS HOLDINGS, INC."),
    ("GEF", "GREIF, INC"),
    ("GEFB", "GREIF, INC"),
    ("GENC", "GENCOR INDUSTRIES INC"),
    ("GEO", "GEO GROUP INC"),
    ("GEOS", "GEOSPACE TECHNOLOGIES CORP"),
    ("GERN", "GERON CORP"),
    ("GETY", "Getty Images Holdings, Inc."),
    ("GFF", "GRIFFON CORP"),
    ("GH", "Guardant Health, Inc."),
    ("GHC", "Graham Holdings Co"),
    ("GHM", "GRAHAM CORP"),
    ("GIC", "GLOBAL INDUSTRIAL Co"),
    ("GIII", "G III APPAREL GROUP LTD /DE/"),
    ("GKOS", "GLAUKOS Corp"),
    ("GLDD", "Great Lakes Dredge & Dock CORP"),
    ("GLNG", "GOLAR LNG LTD"),
    ("GLRE", "GREENLIGHT CAPITAL RE, LTD."),
    ("GLSI", "Greenwich LifeSciences, Inc."),
    ("GLUE", "Monte Rosa Therapeutics, Inc."),
    ("GMGI", "Golden Matrix Group, Inc."),
    ("GMRE", "Global Medical REIT Inc."),
    ("GMS", "GMS Inc."),
    ("GNE", "Genie Energy Ltd."),
    ("GNK", "GENCO SHIPPING & TRADING LTD"),
    ("GNL", "Global Net Lease, Inc."),
    ("GNTY", "GUARANTY BANCSHARES INC /TX/"),
    ("GNW", "GENWORTH FINANCIAL INC"),
    ("GOCO", "GoHealth, Inc."),
    ("GOGL", "Golden Ocean Group Ltd"),
    ("GOGO", "Gogo Inc."),
    ("GOLF", "Acushnet Holdings Corp."),
    ("GOOD", "GLADSTONE COMMERCIAL CORP"),
    ("GPI", "GROUP 1 AUTOMOTIVE INC"),
    ("GPMT", "Granite Point Mortgage Trust Inc."),
    ("GPOR", "GULFPORT ENERGY CORP"),
    ("GPRE", "Green Plains Inc."),
    ("GPRO", "GoPro, Inc."),
    ("GRBK", "Green Brick Partners, Inc."),
    ("GRC", "GORMAN RUPP CO"),
    ("GRDN", "Guardian Pharmacy Services, Inc."),
    ("GRND", "Grindr Inc."),
    ("GRNT", "Granite Ridge Resources, Inc."),
    ("GRPN", "Groupon, Inc."),
    ("GRWG", "GrowGeneration Corp."),
    ("GSAT", "Globalstar, Inc."),
    ("GSBC", "GREAT SOUTHERN BANCORP, INC."),
    ("GSHD", "Goosehead Insurance, Inc."),
    ("GT", "GOODYEAR TIRE & RUBBER CO /OH/"),
    ("GTLS", "CHART INDUSTRIES INC"),
    ("GTN", "GRAY TELEVISION INC"),
    ("GTXI", ""),
    ("GTY", "GETTY REALTY CORP /MD/"),
    ("GUTS", "FRACTYL HEALTH, INC."),
    ("GVA", "GRANITE CONSTRUCTION INC"),
    ("GWRS", "Global Water Resources, Inc."),
    ("GYRE", "GYRE THERAPEUTICS, INC."),
    ("HAE", "HAEMONETICS CORP"),
    ("HAFC", "HANMI FINANCIAL CORP"),
    ("HAIN", "HAIN CELESTIAL GROUP INC"),
    ("HALO", "HALOZYME THERAPEUTICS, INC."),
    ("HASI", "HA Sustainable Infrastructure Capital, Inc."),
    ("HBB", "Hamilton Beach Brands Holding Co"),
    ("HBCP", "HOME BANCORP, INC."),
    ("HBI", "Hanesbrands Inc."),
    ("HBIO", "HARVARD BIOSCIENCE INC"),
    ("HBNC", "HORIZON BANCORP INC /IN/"),
    ("HBT", "HBT Financial, Inc."),
    ("HCAT", "Health Catalyst, Inc."),
    ("HCC", "WARRIOR MET COAL, INC."),
    ("HCI", "HCI Group, Inc."),
    ("HCKT", "HACKETT GROUP, INC."),
    ("HCSG", "HEALTHCARE SERVICES GROUP INC"),
    ("HDSN", "HUDSON TECHNOLOGIES INC /NY"),
    ("HE", "HAWAIIAN ELECTRIC INDUSTRIES INC"),
    ("HEES", "H&E Equipment Services, Inc."),
    ("HELE", "HELEN OF TROY LTD"),
    ("HFFG", "HF Foods Group Inc."),
    ("HFWA", "HERITAGE FINANCIAL CORP /WA/"),
    ("HG", "Hamilton Insurance Group, Ltd."),
    ("HGV", "Hilton Grand Vacations Inc."),
    ("HI", "Hillenbrand, Inc."),
    ("HIFS", "Hingham Institution for Savings"),
    ("HIMS", "Hims & Hers Health, Inc."),
    ("HIPO", "Hippo Holdings Inc."),
    ("HL", "HECLA MINING CO/DE/"),
    ("HLF", "HERBALIFE LTD."),
    ("HLIO", "HELIOS TECHNOLOGIES, INC."),
    ("HLIT", "HARMONIC INC"),
    ("HLLY", "Holley Inc."),
    ("HLMN", "Hillman Solutions Corp."),
    ("HLNE", "Hamilton Lane INC"),
    ("HLVX", "HilleVax, Inc."),
    ("HLX", "HELIX ENERGY SOLUTIONS GROUP INC"),
    ("HMN", "HORACE MANN EDUCATORS CORP /DE/"),
    ("HMST", "HomeStreet, Inc."),
    ("HNI", "HNI CORP"),
    ("HNRG", "HALLADOR ENERGY CO"),
    ("HNST", "Honest Company, Inc."),
    ("HOFT", "HOOKER FURNISHINGS Corp"),
    ("HOMB", "HOME BANCSHARES INC"),
    ("HONE", "HarborOne Bancorp, Inc."),
    ("HOPE", "HOPE BANCORP INC"),
    ("HOUS", "Anywhere Real Estate Inc."),
    ("HOV", "HOVNANIAN ENTERPRISES INC"),
    ("HOWL", "Werewolf Therapeutics, Inc."),
    ("HP", "Helmerich & Payne, Inc."),
    ("HPK", "HighPeak Energy, Inc."),
    ("HPP", "Hudson Pacific Properties, Inc."),
    ("HQI", "HireQuest, Inc."),
    ("HQY", "HEALTHEQUITY, INC."),
    ("HRI", "HERC HOLDINGS INC"),
    ("HRMY", "Harmony Biosciences Holdings, Inc."),
    ("HROW", "HARROW, INC."),
    ("HRTG", "Heritage Insurance Holdings, Inc."),
    ("HRTX", "HERON THERAPEUTICS, INC. /DE/"),
    ("HSHP", "Himalaya Shipping Ltd."),
    ("HSII", "HEIDRICK & STRUGGLES INTERNATIONAL INC"),
    ("HSTM", "HEALTHSTREAM INC"),
    ("HTB", "HomeTrust Bancshares, Inc."),
    ("HTBK", "HERITAGE COMMERCE CORP"),
    ("HTH", "Hilltop Holdings Inc."),
    ("HTLD", "HEARTLAND EXPRESS INC"),
    ("HTZ", "HERTZ GLOBAL HOLDINGS, INC"),
    ("HUBG", "Hub Group, Inc."),
    ("HUMA", "Humacyte, Inc."),
    ("HURN", "Huron Consulting Group Inc."),
    ("HUT", "Hut 8 Corp."),
    ("HVT", "HAVERTY FURNITURE COMPANIES INC"),
    ("HWC", "HANCOCK WHITNEY CORP"),
    ("HWKN", "HAWKINS INC"),
    ("HY", "HYSTER-YALE, INC."),
    ("HYLN", "Hyliion Holdings Corp."),
    ("HZO", "MARINEMAX INC"),
    ("IART", "INTEGRA LIFESCIENCES HOLDINGS CORP"),
    ("IAS", "INTEGRAL AD SCIENCE HOLDING CORP."),
    ("IAUX", "i-80 Gold Corp."),
    ("IBCP", "INDEPENDENT BANK CORP /MI/"),
    ("IBEX", "IBEX Ltd"),
    ("IBOC", "INTERNATIONAL BANCSHARES CORP"),
    ("IBP", "Installed Building Products, Inc."),
    ("IBRX", "ImmunityBio, Inc."),
    ("IBTA", "Ibotta, Inc."),
    ("ICFI", "ICF International, Inc."),
    ("ICHR", "ICHOR HOLDINGS, LTD."),
    ("ICUI", "ICU MEDICAL INC/DE"),
    ("IDCC", "InterDigital, Inc."),
    ("IDT", "IDT CORP"),
    ("IDYA", "IDEAYA Biosciences, Inc."),
    ("IE", "Ivanhoe Electric Inc."),
    ("IESC", "IES Holdings, Inc."),
    ("IGMS", "IGM Biosciences, Inc."),
    ("IGT", "International Game Technology PLC"),
    ("IHRT", "iHeartMedia, Inc."),
    ("III", "Information Services Group Inc."),
    ("IIIN", "INSTEEL INDUSTRIES INC"),
    ("IIIV", "i3 Verticals, Inc."),
    ("IIPR", "INNOVATIVE INDUSTRIAL PROPERTIES INC"),
    ("ILPT", "Industrial Logistics Properties Trust"),
    ("IMAX", "IMAX CORP"),
    ("IMKTA", "INGLES MARKETS INC"),
    ("IMMR", "IMMERSION CORP"),
    ("IMNM", "Immunome Inc."),
    ("IMVT", "Immunovant, Inc."),
    ("IMXI", "International Money Express, Inc."),
    ("INBK", "First Internet Bancorp"),
    ("INBX", "Inhibrx Biosciences, Inc."),
    ("INDB", "INDEPENDENT BANK CORP"),
    ("INDI", "indie Semiconductor, Inc."),
    ("INFU", "InfuSystem Holdings, Inc"),
    ("INGN", "Inogen Inc"),
    ("INH", "Indus Holding AG"),
    ("INMB", "Inmune Bio, Inc."),
    ("INMD", "InMode Ltd."),
    ("INN", "Summit Hotel Properties, Inc."),
    ("INNV", "InnovAge Holding Corp."),
    ("INO", "INOVIO PHARMACEUTICALS, INC."),
    ("INOD", "INNODATA INC"),
    ("INR", "Infinity Natural Resources Inc."),
    ("INSE", "Inspired Entertainment, Inc."),
    ("INSM", "INSMED Inc"),
    ("INSW", "International Seaways, Inc."),
    ("INTA", "Intapp, Inc."),
    ("INVA", "Innoviva, Inc."),
    ("INVX", "Innovex International, Inc."),
    ("INZY", "Inozyme Pharma, Inc."),
    ("IONQ", "IonQ, Inc."),
    ("IOSP", "INNOSPEC INC."),
    ("IOVA", "IOVANCE BIOTHERAPEUTICS, INC."),
    ("IPAR", "INTERPARFUMS INC"),
    ("IPI", "Intrepid Potash, Inc."),
    ("IPSC", "Century Therapeutics, Inc."),
    ("IRBT", "IROBOT CORP"),
    ("IRMD", "IRADIMED CORP"),
    ("IRON", "Disc Medicine, Inc."),
    ("IRT", "INDEPENDENCE REALTY TRUST, INC."),
    ("IRTC", "iRhythm Technologies, Inc."),
    ("IRWD", "IRONWOOD PHARMACEUTICALS INC"),
    ("ISPR", "Ispire Technology Inc."),
    ("ISTR", "Investar Holding Corp"),
    ("ITGR", "Integer Holdings Corp"),
    ("ITIC", "INVESTORS TITLE CO"),
    ("ITOS", "iTeos Therapeutics, Inc."),
    ("ITRI", "ITRON, INC."),
    ("IVR", "Invesco Mortgage Capital Inc."),
    ("IVT", "InvenTrust Properties Corp."),
    ("IVVD", "Invivyd, Inc."),
    ("JACK", "JACK IN THE BOX INC"),
    ("JAKK", "JAKKS PACIFIC INC"),
    ("JAMF", "Jamf Holding Corp."),
    ("JANX", "Janux Therapeutics, Inc."),
    ("JBGS", "JBG SMITH Properties"),
    ("JBI", "Janus International Group, Inc."),
    ("JBLU", "JETBLUE AIRWAYS CORP"),
    ("JBSS", "SANFILIPPO JOHN B & SON INC"),
    ("JBTM", "JBT Marel Corp"),
    ("JELD", "JELD-WEN Holding, Inc."),
    ("JILL", "J.Jill, Inc."),
    ("JJSF", "J&J SNACK FOODS CORP"),
    ("JMSB", "John Marshall Bancorp, Inc."),
    ("JOBY", "Joby Aviation, Inc."),
    ("JOE", "ST JOE Co"),
    ("JOUT", "JOHNSON OUTDOORS INC"),
    ("JRVR", "James River Group Holdings, Ltd."),
    ("JSPR", "Jasper Therapeutics, Inc."),
    ("JXN", "Jackson Financial Inc."),
    ("JYNT", "JOINT Corp"),
    ("KAI", "KADANT INC"),
    ("KALU", "KAISER ALUMINUM CORP"),
    ("KALV", "KalVista Pharmaceuticals, Inc."),
    ("KAR", "OPENLANE, Inc."),
    ("KBH", "KB HOME"),
    ("KE", "Kimball Electronics, Inc."),
    ("KELYA", "KELLY SERVICES INC"),
    ("KFRC", "KFORCE INC"),
    ("KFS", "KINGSWAY FINANCIAL SERVICES INC"),
    ("KFY", "KORN FERRY"),
    ("KGS", "Kodiak Gas Services, Inc."),
    ("KIDS", "ORTHOPEDIATRICS CORP"),
    ("KIND", "Nextdoor Holdings, Inc."),
    ("KLC", "KinderCare Learning Companies, Inc."),
    ("KLG", "WK Kellogg Co"),
    ("KLIC", "KULICKE & SOFFA INDUSTRIES INC"),
    ("KLTR", "KALTURA INC"),
    ("KMT", "KENNAMETAL INC"),
    ("KN", "Knowles Corp"),
    ("KNF", "Knife River Corp"),
    ("KNSA", "Kiniksa Pharmaceuticals International, plc"),
    ("KNTK", "Kinetik Holdings Inc."),
    ("KOD", "Kodiak Sciences Inc."),
    ("KODK", "EASTMAN KODAK CO"),
    ("KOP", "Koppers Holdings Inc."),
    ("KOS", "Kosmos Energy Ltd."),
    ("KREF", "KKR Real Estate Finance Trust Inc."),
    ("KRG", "KITE REALTY GROUP TRUST"),
    ("KRNY", "Kearny Financial Corp."),
    ("KRO", "KRONOS WORLDWIDE INC"),
    ("KROS", "Keros Therapeutics, Inc."),
    ("KRRO", "Korro Bio, Inc."),
    ("KRT", "Karat Packaging Inc."),
    ("KRUS", "KURA SUSHI USA, INC."),
    ("KRYS", "Krystal Biotech, Inc."),
    ("KTB", "Kontoor Brands, Inc."),
    ("KTOS", "KRATOS DEFENSE & SECURITY SOLUTIONS, INC."),
    ("KURA", "Kura Oncology, Inc."),
    ("KW", "Kennedy-Wilson Holdings, Inc."),
    ("KWR", "QUAKER CHEMICAL CORP"),
    ("KYMR", "Kymera Therapeutics, Inc."),
    ("KYTX", "Kyverna Therapeutics, Inc."),
    ("LAB", "STANDARD BIOTOOLS INC."),
    ("LADR", "Ladder Capital Corp"),
    ("LANC", "LANCASTER COLONY CORP"),
    ("LAND", "GLADSTONE LAND Corp"),
    ("LASR", "NLIGHT, INC."),
    ("LAUR", "LAUREATE EDUCATION, INC."),
    ("LAW", "CS Disco, Inc."),
    ("LAZR", "Luminar Technologies, Inc./DE"),
    ("LBRT", "Liberty Energy Inc."),
    ("LC", "LendingClub Corp"),
    ("LCII", "LCI INDUSTRIES"),
    ("LCNB", "LCNB CORP"),
    ("LCTX", "Lineage Cell Therapeutics, Inc."),
    ("LCUT", "LIFETIME BRANDS, INC"),
    ("LE", "LANDS' END, INC."),
    ("LEGH", "Legacy Housing Corp"),
    ("LENZ", "LENZ Therapeutics, Inc."),
    ("LESL", "Leslie's, Inc."),
    ("LEU", "CENTRUS ENERGY CORP"),
    ("LFCR", "LIFECORE BIOMEDICAL, INC. DE"),
    ("LFMD", "LifeMD, Inc."),
    ("LFST", "LifeStance Health Group, Inc."),
    ("LGFA", "LIONS GATE ENTERTAINMENT CORP /CN/"),
    ("LGFB", "LIONS GATE ENTERTAINMENT CORP /CN/"),
    ("LGIH", "LGI Homes, Inc."),
    ("LGND", "LIGAND PHARMACEUTICALS INC"),
    ("LGTY", "LOGILITY SUPPLY CHAIN SOLUTIONS, INC"),
    ("LIF", "Life360, Inc."),
    ("LILA", "Liberty Latin America Ltd."),
    ("LILAK", "Liberty Latin America Ltd."),
    ("LINC", "LINCOLN EDUCATIONAL SERVICES CORP"),
    ("LIND", "LINDBLAD EXPEDITIONS HOLDINGS, INC."),
    ("LIVN", "LivaNova PLC"),
    ("LKFN", "LAKELAND FINANCIAL CORP"),
    ("LMAT", "LEMAITRE VASCULAR INC"),
    ("LMB", "Limbach Holdings, Inc."),
    ("LMND", "Lemonade, Inc."),
    ("LMNR", "Limoneira CO"),
    ("LNKB", "LINKBANCORP, Inc."),
    ("LNN", "LINDSAY CORP"),
    ("LNTH", "Lantheus Holdings, Inc."),
    ("LNZA", "LanzaTech Global, Inc."),
    ("LOB", "Live Oak Bancshares, Inc."),
    ("LOCO", "El Pollo Loco Holdings, Inc."),
    ("LOVE", "Lovesac Co"),
    ("LPG", "DORIAN LPG LTD."),
    ("LPRO", "Open Lending Corp"),
    ("LQDA", "Liquidia Corp"),
    ("LQDT", "LIQUIDITY SERVICES INC"),
    ("LRMR", "Larimar Therapeutics, Inc."),
    ("LRN", "Stride, Inc."),
    ("LSEA", "Landsea Homes Corp"),
    ("LTC", "LTC PROPERTIES INC"),
    ("LTH", "Life Time Group Holdings, Inc."),
    ("LUMN", "Lumen Technologies, Inc."),
    ("LUNG", "Pulmonx Corp"),
    ("LUNR", "Intuitive Machines, Inc."),
    ("LVO", "LiveOne, Inc."),
    ("LVWR", "LiveWire Group, Inc."),
    ("LWAY", "Lifeway Foods, Inc."),
    ("LWLG", "Lightwave Logic, Inc."),
    ("LXEO", "Lexeo Therapeutics, Inc."),
    ("LXFR", "LUXFER HOLDINGS PLC"),
    ("LXP", "LXP Industrial Trust"),
    ("LXRX", "LEXICON PHARMACEUTICALS, INC."),
    ("LXU", "LSB INDUSTRIES, INC."),
    ("LYEL", "Lyell Immunopharma, Inc."),
    ("LYRA", "Lyra Therapeutics, Inc."),
    ("LYTS", "LSI INDUSTRIES INC"),
    ("LZ", "LEGALZOOM.COM, INC."),
    ("LZB", "LA-Z-BOY INC"),
    ("LZM", "Lifezone Metals Ltd"),
    ("MAC", "MACERICH CO"),
    ("MAMA", "Mama's Creations, Inc."),
    ("MAPS", "WM TECHNOLOGY, INC."),
    ("MARA", "MARA Holdings, Inc."),
    ("MASS", "908 Devices Inc."),
    ("MATV", "Mativ Holdings, Inc."),
    ("MATW", "MATTHEWS INTERNATIONAL CORP"),
    ("MATX", "Matson, Inc."),
    ("MAX", "MediaAlpha, Inc."),
    ("MAZE", "Maze Therapeutics Inc."),
    ("MBC", "MasterBrand, Inc."),
    ("MBCN", "MIDDLEFIELD BANC CORP"),
    ("MBI", "MBIA INC"),
    ("MBIN", "Merchants Bancorp"),
    ("MBUU", "MALIBU BOATS, INC."),
    ("MBWM", "MERCANTILE BANK CORP"),
    ("MBX", "MBX Biosciences, Inc."),
    ("MC", "Moelis & Co"),
    ("MCB", "Metropolitan Bank Holding Corp."),
    ("MCBS", "MetroCity Bankshares, Inc."),
    ("MCFT", "MasterCraft Boat Holdings, Inc."),
    ("MCRI", "MONARCH CASINO & RESORT INC"),
    ("MCS", "MARCUS CORP"),
    ("MCW", "Mister Car Wash, Inc."),
    ("MCY", "MERCURY GENERAL CORP"),
    ("MD", "Pediatrix Medical Group, Inc."),
    ("MDGL", "MADRIGAL PHARMACEUTICALS, INC."),
    ("MDWD", "MediWound Ltd."),
    ("MDXG", "MIMEDX GROUP, INC."),
    ("MEC", "Mayville Engineering Company, Inc."),
    ("MED", "MEDIFAST INC"),
    ("MEG", "Montrose Environmental Group, Inc."),
    ("MEI", "METHODE ELECTRONICS INC"),
    ("METCB", "Ramaco Resources, Inc."),
    ("METCV", ""),
    ("MFA", "MFA FINANCIAL, INC."),
    ("MFIN", "MEDALLION FINANCIAL CORP"),
    ("MG", "Mistras Group, Inc."),
    ("MGEE", "MGE ENERGY INC"),
    ("MGNI", "MAGNITE, INC."),
    ("MGNX", "MACROGENICS INC"),
    ("MGPI", "MGP INGREDIENTS INC"),
    ("MGRC", "MCGRATH RENTCORP"),
    ("MGTX", "MeiraGTx Holdings plc"),
    ("MGX", "Metagenomi, Inc."),
    ("MGY", "Magnolia Oil & Gas Corp"),
    ("MHLD", "Maiden Holdings, Ltd."),
    ("MHO", "M/I HOMES, INC."),
    ("MIR", "Mirion Technologies, Inc."),
    ("MIRM", "Mirum Pharmaceuticals, Inc."),
    ("MITK", "MITEK SYSTEMS INC"),
    ("MITT", "AG Mortgage Investment Trust, Inc."),
    ("MKTW", "MARKETWISE, INC."),
    ("ML", "MONEYLION INC."),
    ("MLAB", "MESA LABORATORIES INC /CO/"),
    ("MLI", "MUELLER INDUSTRIES INC"),
    ("MLKN", "MILLERKNOLL, INC."),
    ("MLNK", "MeridianLink, Inc."),
    ("MLP", "MAUI LAND & PINEAPPLE CO INC"),
    ("MLR", "MILLER INDUSTRIES INC /TN/"),
    ("MLYS", "Mineralys Therapeutics, Inc."),
    ("MMI", "Marcus & Millichap, Inc."),
    ("MMS", "MAXIMUS, INC."),
    ("MMSI", "MERIT MEDICAL SYSTEMS INC"),
    ("MNKD", "MANNKIND CORP"),
    ("MNMD", "Mind Medicine (MindMed) Inc."),
    ("MNRO", "MONRO, INC."),
    ("MNTK", "Montauk Renewables, Inc."),
    ("MOD", "MODINE MANUFACTURING CO"),
    ("MODG", "Topgolf Callaway Brands Corp."),
    ("MODV", "ModivCare Inc"),
    ("MOFG", "MidWestOne Financial Group, Inc."),
    ("MOGA", ""),
    ("MOV", "MOVADO GROUP INC"),
    ("MPB", "MID PENN BANCORP INC"),
    ("MPX", "MARINE PRODUCTS CORP"),
    ("MQ", "Marqeta, Inc."),
    ("MRAM", "EVERSPIN TECHNOLOGIES INC"),
    ("MRC", "MRC GLOBAL INC."),
    ("MRCY", "MERCURY SYSTEMS INC"),
    ("MRSN", "Mersana Therapeutics, Inc."),
    ("MRTN", "MARTEN TRANSPORT LTD"),
    ("MRVI", "MARAVAI LIFESCIENCES HOLDINGS, INC."),
    ("MSBI", "Midland States Bancorp, Inc."),
    ("MSEX", "MIDDLESEX WATER CO"),
    ("MSFUT", ""),
    ("MSGE", "Madison Square Garden Entertainment Corp."),
    ("MTAL", "MAC Copper Ltd"),
    ("MTH", "Meritage Homes CORP"),
    ("MTRN", "MATERION Corp"),
    ("MTRX", "MATRIX SERVICE CO"),
    ("MTSR", "Metsera, Inc."),
    ("MTUS", "Metallus Inc."),
    ("MTW", "MANITOWOC CO INC"),
    ("MTX", "MINERALS TECHNOLOGIES INC"),
    ("MUR", "MURPHY OIL CORP"),
    ("MVBF", "MVB FINANCIAL CORP"),
    ("MVIS", "MICROVISION, INC."),
    ("MWA", "Mueller Water Products, Inc."),
    ("MXCT", "MAXCYTE, INC."),
    ("MXL", "MAXLINEAR, INC"),
    ("MYE", "MYERS INDUSTRIES INC"),
    ("MYFW", "First Western Financial Inc"),
    ("MYGN", "MYRIAD GENETICS INC"),
    ("MYPS", "PLAYSTUDIOS, Inc."),
    ("MYRG", "MYR GROUP INC."),
    ("NABL", "N-able, Inc."),
    ("NAGE", "ChromaDex Corp."),
    ("NAT", "NORDIC AMERICAN TANKERS Ltd"),
    ("NATH", "NATHANS FAMOUS, INC."),
    ("NATL", "NCR Atleos Corp"),
    ("NATR", "NATURES SUNSHINE PRODUCTS INC"),
    ("NAUT", "Nautilus Biotechnology, Inc."),
    ("NAVI", "NAVIENT CORP"),
    ("NBBK", "NB Bancorp Inc."),
    ("NBHC", "National Bank Holdings Corp"),
    ("NBN", "Northeast Bank"),
    ("NBR", "NABORS INDUSTRIES LTD"),
    ("NBTB", "NBT BANCORP INC"),
    ("NC", "NACCO INDUSTRIES INC"),
    ("NCMI", "National CineMedia, Inc."),
    ("NE", "Noble Corp plc"),
    ("NECB", "NorthEast Community Bancorp, Inc./MD/"),
    ("NEO", "NEOGENOMICS INC"),
    ("NEOG", "NEOGEN CORP"),
    ("NEWT", "NewtekOne, Inc."),
    ("NEXT", "NextDecade Corp."),
    ("NFBK", "Northfield Bancorp, Inc."),
    ("NG", "NOVAGOLD RESOURCES INC"),
    ("NGNE", "Neurogene Inc."),
    ("NGS", "NATURAL GAS SERVICES GROUP INC"),
    ("NGVC", "Natural Grocers by Vitamin Cottage, Inc."),
    ("NGVT", "Ingevity Corp"),
    ("NHC", "NATIONAL HEALTHCARE CORP"),
    ("NHI", "NATIONAL HEALTH INVESTORS INC"),
    ("NIC", "NICOLET BANKSHARES INC"),
    ("NJR", "NEW JERSEY RESOURCES CORP"),
    ("NKSH", "NATIONAL BANKSHARES INC"),
    ("NKTR", "NEKTAR THERAPEUTICS"),
    ("NKTX", "Nkarta, Inc."),
    ("NL", "NL INDUSTRIES INC"),
    ("NLOP", "Net Lease Office Properties"),
    ("NMIH", "NMI Holdings, Inc."),
    ("NMRA", "Neumora Therapeutics, Inc."),
    ("NMRK", "NEWMARK GROUP, INC."),
    ("NN", "NEXTNAV INC."),
    ("NNBR", "NN INC"),
    ("NNE", "Nano Nuclear Energy Inc."),
    ("NNI", "NELNET INC"),
    ("NNOX", "Nano-X Imaging Ltd."),
    ("NODK", "NI Holdings, Inc."),
    ("NOG", "NORTHERN OIL & GAS, INC."),
    ("NOTE", "FiscalNote Holdings, Inc."),
    ("NOVA", "Sunnova Energy International Inc."),
    ("NOVT", "NOVANTA INC"),
    ("NPCE", "NeuroPace Inc"),
    ("NPK", "NATIONAL PRESTO INDUSTRIES INC"),
    ("NPKI", "NPK International Inc."),
    ("NPO", "Enpro Inc."),
    ("NPWR", "Net Power Inc."),
    ("NRC", "NATIONAL RESEARCH CORP"),
    ("NRDS", "NERDWALLET, INC."),
    ("NRDY", "Nerdy Inc."),
    ("NREF", "NexPoint Real Estate Finance, Inc."),
    ("NRGV", "Energy Vault Holdings, Inc."),
    ("NRIM", "NORTHRIM BANCORP INC"),
    ("NRIX", "Nurix Therapeutics, Inc."),
    ("NSIT", "INSIGHT ENTERPRISES INC"),
    ("NSP", "INSPERITY, INC."),
    ("NSSC", "NAPCO SECURITY TECHNOLOGIES, INC"),
    ("NTB", "Bank of N.T. Butterfield & Son Ltd"),
    ("NTCT", "NETSCOUT SYSTEMS INC"),
    ("NTGR", "NETGEAR, INC."),
    ("NTIC", "NORTHERN TECHNOLOGIES INTERNATIONAL CORP"),
    ("NTLA", "Intellia Therapeutics, Inc."),
    ("NTST", "NETSTREIT Corp."),
    ("NUS", "NU SKIN ENTERPRISES, INC."),
    ("NUVB", "Nuvation Bio Inc."),
    ("NUVL", "Nuvalent, Inc."),
    ("NVAX", "NOVAVAX INC"),
    ("NVCR", "NovoCure Ltd"),
    ("NVEC", "NVE CORP /NEW/"),
    ("NVEE", "NV5 Global, Inc."),
    ("NVRI", "ENVIRI Corp"),
    ("NVTS", "Navitas Semiconductor Corp"),
    ("NWBI", "Northwest Bancshares, Inc."),
    ("NWE", "NorthWestern Energy Group, Inc."),
    ("NWFL", "NORWOOD FINANCIAL CORP"),
    ("NWN", "NORTHWEST NATURAL GAS CO"),
    ("NWPX", "NORTHWEST PIPE CO"),
    ("NX", "Quanex Building Products CORP"),
    ("NXDT", "NEXPOINT DIVERSIFIED REAL ESTATE TRUST"),
    ("NXRT", "NexPoint Residential Trust, Inc."),
    ("NXT", "Nextracker Inc."),
    ("NYMT", "NEW YORK MORTGAGE TRUST, INC."),
    ("OABI", "OmniAb, Inc."),
    ("OB", "Outbrain Inc."),
    ("OBIO", "Orchestra BioMed Holdings, Inc."),
    ("OBK", "Origin Bancorp, Inc."),
    ("OBT", "Orange County Bancorp, Inc. /DE/"),
    ("OCFC", "OCEANFIRST FINANCIAL CORP"),
    ("OCGN", "Ocugen, Inc."),
    ("OCUL", "OCULAR THERAPEUTIX, INC"),
    ("ODC", "Oil-Dri Corp of America"),
    ("ODP", "ODP Corp"),
    ("OEC", "Orion S.A."),
    ("OFG", "OFG BANCORP"),
    ("OFIX", "Orthofix Medical Inc."),
    ("OFLX", "Omega Flex, Inc."),
    ("OGS", "ONE Gas, Inc."),
    ("OI", "O-I Glass, Inc. /DE/"),
    ("OII", "OCEANEERING INTERNATIONAL INC"),
    ("OIS", "OIL STATES INTERNATIONAL, INC"),
    ("OLMA", "Olema Pharmaceuticals, Inc."),
    ("OLO", "Olo Inc."),
    ("OLP", "ONE LIBERTY PROPERTIES INC"),
    ("OLPX", "OLAPLEX HOLDINGS, INC."),
    ("OMCL", "OMNICELL, INC."),
    ("OMER", "OMEROS CORP"),
    ("OMI", "OWENS & MINOR INC/VA/"),
    ("ONB", "OLD NATIONAL BANCORP /IN/"),
    ("ONEW", "OneWater Marine Inc."),
    ("ONIT", "ONITY GROUP INC."),
    ("ONL", "Orion Office REIT Inc."),
    ("ONTF", "ON24 INC."),
    ("OOMA", "OOMA INC"),
    ("OPAD", "Offerpad Solutions Inc."),
    ("OPCH", "Option Care Health, Inc."),
    ("OPEN", "Opendoor Technologies Inc."),
    ("OPFI", "OppFi Inc."),
    ("OPK", "OPKO HEALTH, INC."),
    ("OPRX", "OptimizeRx Corp"),
    ("ORA", "ORMAT TECHNOLOGIES, INC."),
    ("ORC", "Orchid Island Capital, Inc."),
    ("ORGO", "Organogenesis Holdings Inc."),
    ("ORIC", "Oric Pharmaceuticals, Inc."),
    ("ORN", "Orion Group Holdings Inc"),
    ("ORRF", "ORRSTOWN FINANCIAL SERVICES INC"),
    ("OSBC", "OLD SECOND BANCORP INC"),
    ("OSCR", "Oscar Health, Inc."),
    ("OSIS", "OSI SYSTEMS INC"),
    ("OSPN", "OneSpan Inc."),
    ("OSUR", "ORASURE TECHNOLOGIES INC"),
    ("OSW", "ONESPAWORLD HOLDINGS Ltd"),
    ("OTLK", "Outlook Therapeutics, Inc."),
    ("OTTR", "Otter Tail Corp"),
    ("OUST", "Ouster, Inc."),
    ("OUT", "OUTFRONT Media Inc."),
    ("OVID", "Ovid Therapeutics Inc."),
    ("OVLY", "Oak Valley Bancorp"),
    ("OXM", "OXFORD INDUSTRIES INC"),
    ("PACB", "PACIFIC BIOSCIENCES OF CALIFORNIA, INC."),
    ("PACK", "Ranpak Holdings Corp."),
    ("PACS", "Pacs Group Inc."),
    ("PAGS", "PagSeguro Digital Ltd."),
    ("PAHC", "PHIBRO ANIMAL HEALTH CORP"),
    ("PAL", "Proficient Auto Logistics, Inc"),
    ("PAMT", "PAMT CORP"),
    ("PANL", "Pangaea Logistics Solutions Ltd."),
    ("PAR", "PAR TECHNOLOGY CORP"),
    ("PARR", "PAR PACIFIC HOLDINGS, INC."),
    ("PATK", "PATRICK INDUSTRIES INC"),
    ("PAX", "Patria Investments Ltd"),
    ("PAYO", "Payoneer Global Inc."),
    ("PAYS", "Paysign, Inc."),
    ("PBF", "PBF Energy Inc."),
    ("PBFS", "Pioneer Bancorp, Inc./MD"),
    ("PBH", "Prestige Consumer Healthcare Inc."),
    ("PBI", "PITNEY BOWES INC /DE/"),
    ("PBPB", "POTBELLY CORP"),
    ("PBYI", "PUMA BIOTECHNOLOGY, INC."),
    ("PCB", "PCB BANCORP"),
    ("PCH", "POTLATCHDELTIC CORP"),
    ("PCRX", "Pacira BioSciences, Inc."),
    ("PCT", "PureCycle Technologies, Inc."),
    ("PCVX", "Vaxcyte, Inc."),
    ("PCYO", "PURE CYCLE CORP"),
    ("PD", "PagerDuty, Inc."),
    ("PDCO", "PATTERSON COMPANIES, INC."),
    ("PDFS", "PDF SOLUTIONS INC"),
    ("PDLB", "Ponce Financial Group, Inc."),
    ("PDLI", ""),
    ("PDM", "Piedmont Office Realty Trust, Inc."),
    ("PEB", "Pebblebrook Hotel Trust"),
    ("PEBK", "PEOPLES BANCORP OF NORTH CAROLINA INC"),
    ("PEBO", "PEOPLES BANCORP INC"),
    ("PECO", "Phillips Edison & Company, Inc."),
    ("PENG", "Penguin Solutions, Inc."),
    ("PEPG", "PepGen Inc."),
    ("PESI", "PERMA FIX ENVIRONMENTAL SERVICES INC"),
    ("PFBC", "Preferred Bank"),
    ("PFIS", "PEOPLES FINANCIAL SERVICES CORP."),
    ("PFS", "PROVIDENT FINANCIAL SERVICES INC"),
    ("PFSI", "PennyMac Financial Services, Inc."),
    ("PGC", "PEAPACK GLADSTONE FINANCIAL CORP"),
    ("PGEN", "PRECIGEN, INC."),
    ("PGNY", "Progyny, Inc."),
    ("PGRE", "Paramount Group, Inc."),
    ("PGY", "Pagaya Technologies Ltd."),
    ("PHAT", "Phathom Pharmaceuticals, Inc."),
    ("PHIN", "PHINIA INC."),
    ("PHLT", "Performant Healthcare Inc"),
    ("PHR", "Phreesia, Inc."),
    ("PI", "IMPINJ INC"),
    ("PINE", "Alpine Income Property Trust, Inc."),
    ("PIPR", "PIPER SANDLER COMPANIES"),
    ("PJT", "PJT Partners Inc."),
    ("PKBK", "PARKE BANCORP, INC."),
    ("PKE", "PARK AEROSPACE CORP"),
    ("PKOH", "PARK OHIO HOLDINGS CORP"),
    ("PKST", "Peakstone Realty Trust"),
    ("PL", "Planet Labs PBC"),
    ("PLAB", "PHOTRONICS INC"),
    ("PLAY", "Dave & Buster's Entertainment, Inc."),
    ("PLBC", "PLUMAS BANCORP"),
    ("PLL", "Piedmont Lithium Inc."),
    ("PLMR", "Palomar Holdings, Inc."),
    ("PLOW", "DOUGLAS DYNAMICS, INC"),
    ("PLPC", "PREFORMED LINE PRODUCTS CO"),
    ("PLRX", "PLIANT THERAPEUTICS, INC."),
    ("PLSE", "PULSE BIOSCIENCES, INC."),
    ("PLUG", "PLUG POWER INC"),
    ("PLUS", "EPLUS INC"),
    ("PLXS", "PLEXUS CORP"),
    ("PLYM", "Plymouth Industrial REIT, Inc."),
    ("PMT", "PennyMac Mortgage Investment Trust"),
    ("PMTS", "CPI Card Group Inc."),
    ("PNRG", "PRIMEENERGY RESOURCES CORP"),
    ("PNTG", "Pennant Group, Inc."),
    ("POR", "PORTLAND GENERAL ELECTRIC CO /OR/"),
    ("POWI", "POWER INTEGRATIONS INC"),
    ("POWL", "POWELL INDUSTRIES INC"),
    ("POWW", "AMMO, INC."),
    ("PPBI", "PACIFIC PREMIER BANCORP INC"),
    ("PPTA", "PERPETUA RESOURCES CORP."),
    ("PRA", "PROASSURANCE CORP"),
    ("PRAA", "PRA GROUP INC"),
    ("PRAX", "Praxis Precision Medicines, Inc."),
    ("PRCH", "Porch Group, Inc."),
    ("PRCT", "PROCEPT BioRobotics Corp"),
    ("PRDO", "PERDOCEO EDUCATION Corp"),
    ("PRG", "PROG Holdings, Inc."),
    ("PRGS", "PROGRESS SOFTWARE CORP /MA"),
    ("PRIM", "Primoris Services Corp"),
    ("PRK", "PARK NATIONAL CORP /OH/"),
    ("PRKS", "United Parks & Resorts Inc."),
    ("PRLB", "Proto Labs Inc"),
    ("PRLD", "Prelude Therapeutics Inc"),
    ("PRM", "Perimeter Solutions, Inc."),
    ("PRMB", "Primo Water Corp /CN/"),
    ("PRME", "Prime Medicine, Inc."),
    ("PRO", "PROS Holdings, Inc."),
    ("PROK", "PROKIDNEY CORP."),
    ("PROP", "Prairie Operating Co."),
    ("PRPL", "Purple Innovation, Inc."),
    ("PRSU", "Pursuit Attractions & Hospitality, Inc."),
    ("PRTA", "PROTHENA CORP PUBLIC LTD CO"),
    ("PRTH", "Priority Technology Holdings, Inc."),
    ("PRVA", "Privia Health Group, Inc."),
    ("PSFE", "Paysafe Ltd"),
    ("PSMT", "PRICESMART INC"),
    ("PSTL", "Postal Realty Trust, Inc."),
    ("PTCT", "PTC THERAPEUTICS, INC."),
    ("PTEN", "PATTERSON UTI ENERGY INC"),
    ("PTGX", "Protagonist Therapeutics, Inc"),
    ("PTLO", "Portillo's Inc."),
    ("PTON", "PELOTON INTERACTIVE, INC."),
    ("PUBM", "PubMatic, Inc."),
    ("PUMP", "ProPetro Holding Corp."),
    ("PVBC", "Provident Bancorp, Inc. /MD/"),
    ("PWP", "Perella Weinberg Partners"),
    ("PX", "P10, Inc."),
    ("PYXS", "Pyxis Oncology, Inc."),
    ("PZZA", "PAPA JOHNS INTERNATIONAL INC"),
    ("QBTS", "D-Wave Quantum Inc."),
    ("QCRH", "QCR HOLDINGS INC"),
    ("QIPT", "Quipt Home Medical Corp."),
    ("QLYS", "QUALYS, INC."),
    ("QNST", "QUINSTREET, INC"),
    ("QRHC", "Quest Resource Holding Corp"),
    ("QSI", "Quantum-Si Inc"),
    ("QTRX", "Quanterix Corp"),
    ("QTTB", "Q32 Bio Inc."),
    ("QTWO", "Q2 Holdings, Inc."),
    ("QUAD", "Quad/Graphics, Inc."),
    ("QUIK", "QUICKLOGIC Corp"),
    ("RAMP", "LiveRamp Holdings, Inc."),
    ("RAPP", "Rapport Therapeutics, Inc."),
    ("RAPT", "RAPT Therapeutics, Inc."),
    ("RBB", "RBB Bancorp"),
    ("RBBN", "Ribbon Communications Inc."),
    ("RBCAA", "REPUBLIC BANCORP INC /KY/"),
    ("RC", "Ready Capital Corp"),
    ("RCEL", "AVITA Medical, Inc."),
    ("RCKT", "ROCKET PHARMACEUTICALS, INC."),
    ("RCKY", "ROCKY BRANDS, INC."),
    ("RCUS", "Arcus Biosciences, Inc."),
    ("RDFN", "Redfin Corp"),
    ("RDN", "RADIAN GROUP INC"),
    ("RDNT", "RadNet, Inc."),
    ("RDUS", "RADIUS RECYCLING, INC."),
    ("RDVT", "Red Violet, Inc."),
    ("RDW", "Redwire Corp"),
    ("RDZN", "Roadzen Inc."),
    ("REAL", "TheRealReal, Inc."),
    ("REAX", "Real Brokerage Inc"),
    ("REFI", "Chicago Atlantic Real Estate Finance, Inc."),
    ("REI", "RING ENERGY, INC."),
    ("REKR", "Rekor Systems, Inc."),
    ("RELL", "RICHARDSON ELECTRONICS, LTD."),
    ("RELY", "Remitly Global, Inc."),
    ("RENB", "RENOVARO INC."),
    ("REPL", "Replimune Group, Inc."),
    ("REPX", "Riley Exploration Permian, Inc."),
    ("RES", "RPC INC"),
    ("REVG", "REV Group, Inc."),
    ("REX", "REX AMERICAN RESOURCES Corp"),
    ("REZI", "RESIDEO TECHNOLOGIES, INC."),
    ("RGCO", "RGC RESOURCES INC"),
    ("RGLS", "Regulus Therapeutics Inc."),
    ("RGNX", "REGENXBIO Inc."),
    ("RGP", "RESOURCES CONNECTION, INC."),
    ("RGR", "STURM RUGER & CO INC"),
    ("RGTI", "Rigetti Computing, Inc."),
    ("RHLD", "Resolute Holdings Management"),
    ("RHP", "Ryman Hospitality Properties, Inc."),
    ("RICK", "RCI HOSPITALITY HOLDINGS, INC."),
    ("RIG", "Transocean Ltd."),
    ("RIGL", "RIGEL PHARMACEUTICALS INC"),
    ("RILY", "B. Riley Financial, Inc."),
    ("RIOT", "Riot Platforms, Inc."),
    ("RKLB", "Rocket Lab USA, Inc."),
    ("RLAY", "Relay Therapeutics, Inc."),
    ("RLGT", "RADIANT LOGISTICS, INC"),
    ("RLJ", "RLJ Lodging Trust"),
    ("RM", "Regional Management Corp."),
    ("RMAX", "RE/MAX Holdings, Inc."),
    ("RMBL", "RumbleOn, Inc."),
    ("RMBS", "RAMBUS INC"),
    ("RMNI", "Rimini Street, Inc."),
    ("RMR", "RMR GROUP INC."),
    ("RNA", "Avidity Biosciences, Inc."),
    ("RNAC", "Cartesian Therapeutics, Inc."),
    ("RNGR", "Ranger Energy Services, Inc."),
    ("RNST", "RENASANT CORP"),
    ("ROAD", "Construction Partners, Inc."),
    ("ROCK", "GIBRALTAR INDUSTRIES, INC."),
    ("ROG", "ROGERS CORP"),
    ("ROOT", "Root, Inc."),
    ("RPAY", "Repay Holdings Corp"),
    ("RPD", "Rapid7, Inc."),
    ("RRBI", "RED RIVER BANCSHARES INC"),
    ("RRR", "Red Rock Resorts, Inc."),
    ("RSI", "Rush Street Interactive, Inc."),
    ("RSVR", "Reservoir Media, Inc."),
    ("RUN", "Sunrun Inc."),
    ("RUSHA", "RUSH ENTERPRISES INC TX"),
    ("RUSHB", "RUSH ENTERPRISES INC TX"),
    ("RVLV", "Revolve Group, Inc."),
    ("RVMD", "Revolution Medicines, Inc."),
    ("RWT", "REDWOOD TRUST INC"),
    ("RXO", "RXO, Inc."),
    ("RXRX", "RECURSION PHARMACEUTICALS, INC."),
    ("RXT", "Rackspace Technology, Inc."),
    ("RYAM", "RAYONIER ADVANCED MATERIALS INC."),
    ("RYI", "Ryerson Holding Corp"),
    ("RYTM", "RHYTHM PHARMACEUTICALS, INC."),
    ("SABR", "Sabre Corp"),
    ("SAFE", "Safehold Inc."),
    ("SAFT", "SAFETY INSURANCE GROUP INC"),
    ("SAGE", "Sage Therapeutics, Inc."),
    ("SAH", "SONIC AUTOMOTIVE INC"),
    ("SAMG", "Silvercrest Asset Management Group Inc."),
    ("SANA", "Sana Biotechnology, Inc."),
    ("SANM", "SANMINA CORP"),
    ("SATS", "EchoStar CORP"),
    ("SAVA", "CASSAVA SCIENCES INC"),
    ("SB", "SAFE BULKERS, INC."),
    ("SBCF", "SEACOAST BANKING CORP OF FLORIDA"),
    ("SBGI", "Sinclair, Inc."),
    ("SBH", "Sally Beauty Holdings, Inc."),
    ("SBRA", "Sabra Health Care REIT, Inc."),
    ("SBSI", "SOUTHSIDE BANCSHARES INC"),
    ("SBT", "Sterling Bancorp, Inc."),
    ("SCHL", "SCHOLASTIC CORP"),
    ("SCL", "STEPAN CO"),
    ("SCLX", "Scilex Holding Co"),
    ("SCPH", "scPharmaceuticals Inc."),
    ("SCS", "STEELCASE INC"),
    ("SCSC", "SCANSOURCE, INC."),
    ("SCVL", "SHOE CARNIVAL INC"),
    ("SCWO", "374Water Inc."),
    ("SD", "SANDRIDGE ENERGY INC"),
    ("SDGR", "Schrodinger, Inc."),
    ("SDRL", "Seadrill Ltd"),
    ("SEAT", "Vivid Seats Inc."),
    ("SEI", "Solaris Energy Infrastructure, Inc."),
    ("SEM", "SELECT MEDICAL HOLDINGS CORP"),
    ("SEMR", "SEMrush Holdings, Inc."),
    ("SENEA", "Seneca Foods Corp"),
    ("SEPN", "Septerna, Inc."),
    ("SERA", "SERA PROGNOSTICS, INC."),
    ("SES", "SES AI Corp"),
    ("SEVN", "Seven Hills Realty Trust"),
    ("SEZL", "Sezzle Inc."),
    ("SFBS", "ServisFirst Bancshares, Inc."),
    ("SFIX", "Stitch Fix, Inc."),
    ("SFL", "SFL Corp Ltd."),
    ("SFM", "Sprouts Farmers Market, Inc."),
    ("SFNC", "SIMMONS FIRST NATIONAL CORP"),
    ("SFST", "SOUTHERN FIRST BANCSHARES INC"),
    ("SG", "Sweetgreen, Inc."),
    ("SGC", "SUPERIOR GROUP OF COMPANIES, INC."),
    ("SGHC", "Super Group (SGHC) Ltd"),
    ("SGHT", "Sight Sciences, Inc."),
    ("SGRY", "Surgery Partners, Inc."),
    ("SHAK", "Shake Shack Inc."),
    ("SHBI", "SHORE BANCSHARES INC"),
    ("SHEN", "SHENANDOAH TELECOMMUNICATIONS CO/VA/"),
    ("SHLS", "Shoals Technologies Group, Inc."),
    ("SHO", "Sunstone Hotel Investors, Inc."),
    ("SHOO", "STEVEN MADDEN, LTD."),
    ("SHYF", "SHYFT GROUP, INC."),
    ("SIBN", "SI-BONE, Inc."),
    ("SIG", "SIGNET JEWELERS LTD"),
    ("SIGA", "SIGA TECHNOLOGIES INC"),
    ("SIGI", "SELECTIVE INSURANCE GROUP INC"),
    ("SITC", "SITE Centers Corp."),
    ("SITM", "SITIME Corp"),
    ("SJW", "SJW GROUP"),
    ("SKIN", "Beauty Health Co"),
    ("SKT", "TANGER INC."),
    ("SKWD", "Skyward Specialty Insurance Group, Inc."),
    ("SKY", "Champion Homes, Inc."),
    ("SKYE", "Skye Bioscience, Inc."),
    ("SKYH", "Sky Harbour Group Corp"),
    ("SKYT", "SkyWater Technology, Inc"),
    ("SKYW", "SKYWEST INC"),
    ("SLAB", "SILICON LABORATORIES INC."),
    ("SLDB", "Solid Biosciences Inc."),
    ("SLDP", "Solid Power, Inc."),
    ("SLG", "SL GREEN REALTY CORP"),
    ("SLND", "Southland Holdings, Inc."),
    ("SLNO", "SOLENO THERAPEUTICS INC"),
    ("SLP", "Simulations Plus, Inc."),
    ("SLQT", "SelectQuote, Inc."),
    ("SLRN", "ACELYRIN, Inc."),
    ("SLVM", "Sylvamo Corp"),
    ("SM", "SM Energy Co"),
    ("SMBC", "SOUTHERN MISSOURI BANCORP, INC."),
    ("SMBK", "SMARTFINANCIAL INC."),
    ("SMHI", "SEACOR Marine Holdings Inc."),
    ("SMID", "SMITH MIDLAND CORP"),
    ("SMLR", "Semler Scientific, Inc."),
    ("SMMT", "Summit Therapeutics Inc."),
    ("SMP", "STANDARD MOTOR PRODUCTS, INC."),
    ("SMPL", "Simply Good Foods Co"),
    ("SMR", "NUSCALE POWER Corp"),
    ("SMRT", "SmartRent, Inc."),
    ("SMTC", "SEMTECH CORP"),
    ("SMTI", "Sanara MedTech Inc."),
    ("SMXT", "SolarMax Technology, Inc."),
    ("SNBR", "Sleep Number Corp"),
    ("SNCY", "Sun Country Airlines Holdings, Inc."),
    ("SNDA", "SONIDA SENIOR LIVING, INC."),
    ("SNDX", "Syndax Pharmaceuticals Inc"),
    ("SNEX", "StoneX Group Inc."),
    ("SOC", "Sable Offshore Corp."),
    ("SONO", "Sonos Inc"),
    ("SOUN", "SOUNDHOUND AI, INC."),
    ("SPCE", "Virgin Galactic Holdings, Inc"),
    ("SPFI", "SOUTH PLAINS FINANCIAL, INC."),
    ("SPHR", "Sphere Entertainment Co."),
    ("SPIR", "Spire Global, Inc."),
    ("SPNS", "SAPIENS INTERNATIONAL CORP N V"),
    ("SPNT", "SiriusPoint Ltd"),
    ("SPOK", "Spok Holdings, Inc"),
    ("SPRY", "ARS Pharmaceuticals, Inc."),
    ("SPSC", "SPS COMMERCE INC"),
    ("SPT", "Sprout Social, Inc."),
    ("SPTN", "SpartanNash Co"),
    ("SPXC", "SPX Technologies, Inc."),
    ("SR", "SPIRE MISSOURI INC"),
    ("SRCE", "1ST SOURCE CORP"),
    ("SRDX", "SURMODICS INC"),
    ("SRI", "STONERIDGE INC"),
    ("SRRK", "Scholar Rock Holding Corp"),
    ("SSB", "SouthState Corp"),
    ("SSBK", "Southern States Bancshares, Inc."),
    ("SSP", "E.W. SCRIPPS Co"),
    ("SSRM", "SSR MINING INC."),
    ("SST", "System1, Inc."),
    ("SSTI", "SOUNDTHINKING, INC."),
    ("SSTK", "Shutterstock, Inc."),
    ("STAA", "STAAR SURGICAL CO"),
    ("STBA", "S&T BANCORP INC"),
    ("STC", "STEWART INFORMATION SERVICES CORP"),
    ("STEL", "Stellar Bancorp, Inc."),
    ("STEM", "STEM, INC."),
    ("STEP", "StepStone Group Inc."),
    ("STGW", "Stagwell Inc"),
    ("STHO", "Star Holdings"),
    ("STKL", "SunOpta Inc."),
    ("STKS", "ONE Group Hospitality, Inc."),
    ("STNE", "StoneCo Ltd."),
    ("STNG", "Scorpio Tankers Inc."),
    ("STOK", "Stoke Therapeutics, Inc."),
    ("STR", "Sitio Royalties Corp."),
    ("STRA", "Strategic Education, Inc."),
    ("STRL", "STERLING INFRASTRUCTURE, INC."),
    ("STRO", "SUTRO BIOPHARMA, INC."),
    ("STRS", "STRATUS PROPERTIES INC"),
    ("STRW", "Strawberry Fields REIT, Inc."),
    ("STTK", "Shattuck Labs, Inc."),
    ("STXS", "Stereotaxis, Inc."),
    ("SUNS", "Sunrise Realty Trust Inc."),
    ("SUPN", "SUPERNUS PHARMACEUTICALS, INC."),
    ("SVC", "Service Properties Trust"),
    ("SVCO", "Silvaco Group, Inc."),
    ("SVRA", "Savara Inc"),
    ("SVV", "Savers Value Village, Inc."),
    ("SWBI", "SMITH & WESSON BRANDS, INC."),
    ("SWI", "SolarWinds Corporation"),
    ("SWIM", "Latham Group, Inc."),
    ("SWKH", "SWK Holdings Corp"),
    ("SWTX", "SpringWorks Therapeutics, Inc."),
    ("SWX", "Southwest Gas Holdings, Inc."),
    ("SXC", "SunCoke Energy, Inc."),
    ("SXI", "STANDEX INTERNATIONAL CORP/DE/"),
    ("SXT", "SENSIENT TECHNOLOGIES CORP"),
    ("SYBT", "Stock Yards Bancorp, Inc."),
    ("SYNA", "SYNAPTICS Inc"),
    ("SYRE", "Spyre Therapeutics, Inc."),
    ("TALK", "Talkspace, Inc."),
    ("TALO", "TALOS ENERGY INC."),
    ("TARS", "Tarsus Pharmaceuticals, Inc."),
    ("TAYD", "TAYLOR DEVICES, INC."),
    ("TBBK", "Bancorp, Inc."),
    ("TBCH", "Turtle Beach Corp"),
    ("TBI", "TrueBlue, Inc."),
    ("TBPH", "Theravance Biopharma, Inc."),
    ("TCBI", "TEXAS CAPITAL BANCSHARES INC/TX"),
    ("TCBK", "TRICO BANCSHARES /"),
    ("TCBX", "Third Coast Bancshares, Inc."),
    ("TCI", "TRANSCONTINENTAL REALTY INVESTORS INC"),
    ("TCMD", "TACTILE SYSTEMS TECHNOLOGY INC"),
    ("TCRX", "TScan Therapeutics, Inc."),
    ("TCX", "TUCOWS INC /PA/"),
    ("TDOC", "Teladoc Health, Inc."),
    ("TDS", "TELEPHONE & DATA SYSTEMS INC /DE/"),
    ("TDUP", "ThredUp Inc."),
    ("TDW", "TIDEWATER INC"),
    ("TE", "T1 Energy Inc."),
    ("TELO", "Telomir Pharmaceuticals, Inc."),
    ("TENB", "Tenable Holdings, Inc."),
    ("TERN", "Terns Pharmaceuticals, Inc."),
    ("TEX", "TEREX CORP"),
    ("TFIN", "Triumph Financial, Inc."),
    ("TG", "TREDEGAR CORP"),
    ("TGI", "TRIUMPH GROUP INC"),
    ("TGLS", "Tecnoglass Inc."),
    ("TGNA", "TEGNA INC"),
    ("TGTX", "TG THERAPEUTICS, INC."),
    ("TH", "Target Hospitality Corp."),
    ("THFF", "FIRST FINANCIAL CORP /IN/"),
    ("THR", "Thermon Group Holdings, Inc."),
    ("THRD", "Third Harmonic Bio, Inc."),
    ("THRM", "Gentherm Inc"),
    ("THRY", "Thryv Holdings, Inc."),
    ("THS", "TreeHouse Foods, Inc."),
    ("TILE", "INTERFACE INC"),
    ("TIPT", "TIPTREE INC."),
    ("TITN", "Titan Machinery Inc."),
    ("TK", "TEEKAY CORP LTD"),
    ("TLS", "TELOS CORP"),
    ("TLYS", "TILLY'S, INC."),
    ("TMCI", "TREACE MEDICAL CONCEPTS, INC."),
    ("TMDX", "TransMedics Group, Inc."),
    ("TMHC", "Taylor Morrison Home Corp"),
    ("TMP", "TOMPKINS FINANCIAL CORP"),
    ("TNC", "TENNANT CO"),
    ("TNDM", "TANDEM DIABETES CARE INC"),
    ("TNET", "TRINET GROUP, INC."),
    ("TNGX", "Tango Therapeutics, Inc."),
    ("TNK", "TEEKAY TANKERS LTD."),
    ("TNYA", "Tenaya Therapeutics, Inc."),
    ("TOWN", "TowneBank"),
    ("TPB", "Turning Point Brands, Inc."),
    ("TPC", "TUTOR PERINI CORP"),
    ("TPH", "Tri Pointe Homes, Inc."),
    ("TPIC", "TPI COMPOSITES, INC"),
    ("TRAK", "ReposiTrak, Inc."),
    ("TRC", "TEJON RANCH CO"),
    ("TRDA", "Entrada Therapeutics, Inc."),
    ("TREE", "LendingTree, Inc."),
    ("TRMK", "TRUSTMARK CORP"),
    ("TRML", "Tourmaline Bio, Inc."),
    ("TRN", "TRINITY INDUSTRIES INC"),
    ("TRNO", "Terreno Realty Corp"),
    ("TRNS", "TRANSCAT INC"),
    ("TROX", "Tronox Holdings plc"),
    ("TRS", "TRIMAS CORP"),
    ("TRST", "TRUSTCO BANK CORP N Y"),
    ("TRTX", "TPG RE Finance Trust, Inc."),
    ("TRUE", "TrueCar, Inc."),
    ("TRUP", "TRUPANION, INC."),
    ("TRVI", "Trevi Therapeutics, Inc."),
    ("TSBK", "TIMBERLAND BANCORP INC"),
    ("TSHA", "Taysha Gene Therapies, Inc."),
    ("TSQ", "Townsquare Media, Inc."),
    ("TSVT", "2seventy bio, Inc."),
    ("TTEC", "TTEC Holdings, Inc."),
    ("TTGT", "TechTarget Holdings Inc."),
    ("TTI", "TETRA TECHNOLOGIES INC"),
    ("TTMI", "TTM TECHNOLOGIES INC"),
    ("TTSH", "TILE SHOP HOLDINGS, INC."),
    ("TUSK", "MAMMOTH ENERGY SERVICES, INC."),
    ("TVTX", "Travere Therapeutics, Inc."),
    ("TWI", "TITAN INTERNATIONAL INC"),
    ("TWIN", "TWIN DISC INC"),
    ("TWO", "TWO HARBORS INVESTMENT CORP."),
    ("TWST", "Twist Bioscience Corp"),
    ("TXNM", "TXNM ENERGY INC"),
    ("TYRA", "Tyra Biosciences, Inc."),
    ("UBSI", "UNITED BANKSHARES INC/WV"),
    ("UCB", "UNITED COMMUNITY BANKS INC"),
    ("UCTT", "Ultra Clean Holdings, Inc."),
    ("UDMY", "Udemy, Inc."),
    ("UE", "Urban Edge Properties"),
    ("UEC", "URANIUM ENERGY CORP"),
    ("UFCS", "UNITED FIRE GROUP INC"),
    ("UFPI", "UFP INDUSTRIES INC"),
    ("UFPT", "UFP TECHNOLOGIES INC"),
    ("UHG", "United Homes Group, Inc."),
    ("UHT", "UNIVERSAL HEALTH REALTY INCOME TRUST"),
    ("UIS", "UNISYS CORP"),
    ("ULBI", "ULTRALIFE CORP"),
    ("ULCC", "Frontier Group Holdings, Inc."),
    ("ULH", "UNIVERSAL LOGISTICS HOLDINGS, INC."),
    ("UMBF", "UMB FINANCIAL CORP"),
    ("UMH", "UMH PROPERTIES, INC."),
    ("UNF", "UNIFIRST CORP"),
    ("UNFI", "UNITED NATURAL FOODS INC"),
    ("UNIT", "Uniti Group Inc."),
    ("UNTY", "UNITY BANCORP INC /NJ/"),
    ("UP", "Wheels Up Experience Inc."),
    ("UPB", "Upstream Bio, Inc."),
    ("UPBD", "UPBOUND GROUP, INC."),
    ("UPST", "Upstart Holdings, Inc."),
    ("UPWK", "UPWORK, INC"),
    ("URBN", "URBAN OUTFITTERS INC"),
    ("URG", "UR-ENERGY INC"),
    ("URGN", "UroGen Pharma Ltd."),
    ("USCB", "USCB FINANCIAL HOLDINGS, INC."),
    ("USD", "ProShares Ultra Semiconductors"),
    ("USLM", "UNITED STATES LIME & MINERALS INC"),
    ("USNA", "USANA HEALTH SCIENCES INC"),
    ("USPH", "U S PHYSICAL THERAPY INC /NV"),
    ("UTI", "UNIVERSAL TECHNICAL INSTITUTE INC"),
    ("UTL", "UNITIL CORP"),
    ("UTMD", "UTAH MEDICAL PRODUCTS INC"),
    ("UTZ", "Utz Brands, Inc."),
    ("UUUU", "ENERGY FUELS INC"),
    ("UVE", "UNIVERSAL INSURANCE HOLDINGS, INC."),
    ("UVSP", "UNIVEST FINANCIAL Corp"),
    ("UVV", "UNIVERSAL CORP /VA/"),
    ("VABK", "Virginia National Bankshares Corp"),
    ("VAL", "Valaris Ltd"),
    ("VALU", "VALUE LINE INC"),
    ("VBTX", "Veritex Holdings, Inc."),
    ("VC", "VISTEON CORP"),
    ("VCEL", "Vericel Corp"),
    ("VCSA", "Vacasa, Inc."),
    ("VCTR", "Victory Capital Holdings, Inc."),
    ("VCYT", "VERACYTE, INC."),
    ("VECO", "VEECO INSTRUMENTS INC"),
    ("VEL", "Velocity Financial, Inc."),
    ("VERA", "Vera Therapeutics, Inc."),
    ("VERU", "VERU INC."),
    ("VERV", "Verve Therapeutics, Inc."),
    ("VERX", "Vertex, Inc."),
    ("VGAS", "Verde Clean Fuels, Inc."),
    ("VHI", "VALHI INC /DE/"),
    ("VIAV", "VIAVI SOLUTIONS INC."),
    ("VICR", "VICOR CORP"),
    ("VIR", "Vir Biotechnology, Inc."),
    ("VIRC", "VIRCO MFG CORPORATION"),
    ("VITL", "Vital Farms, Inc."),
    ("VLGEA", "VILLAGE SUPER MARKET INC"),
    ("VLY", "VALLEY NATIONAL BANCORP"),
    ("VMD", "VIEMED HEALTHCARE, INC."),
    ("VMEO", "Vimeo, Inc."),
    ("VNDA", "Vanda Pharmaceuticals Inc."),
    ("VPG", "Vishay Precision Group, Inc."),
    ("VRA", "Vera Bradley, Inc."),
    ("VRCA", "Verrica Pharmaceuticals Inc."),
    ("VRDN", "Viridian Therapeutics, Inc."),
    ("VRE", "Veris Residential, Inc."),
    ("VREX", "Varex Imaging Corp"),
    ("VRNS", "VARONIS SYSTEMS INC"),
    ("VRNT", "VERINT SYSTEMS INC"),
    ("VRRM", "VERRA MOBILITY Corp"),
    ("VRTS", "VIRTUS INVESTMENT PARTNERS, INC."),
    ("VSAT", "VIASAT INC"),
    ("VSCO", "Victoria's Secret & Co."),
    ("VSEC", "VSE CORP"),
    ("VSH", "VISHAY INTERTECHNOLOGY INC"),
    ("VSTM", "Verastem, Inc."),
    ("VTLE", "Vital Energy, Inc."),
    ("VTOL", "Bristow Group Inc."),
    ("VTS", "Vitesse Energy, Inc."),
    ("VTSI", "VirTra, Inc"),
    ("VTYX", "Ventyx Biosciences, Inc."),
    ("VVX", "V2X, Inc."),
    ("VYGR", "Voyager Therapeutics, Inc."),
    ("VYX", "NCR Voyix Corp"),
    ("WABC", "WESTAMERICA BANCORPORATION"),
    ("WAFD", "WAFD INC"),
    ("WALD", "Waldencast plc"),
    ("WASH", "WASHINGTON TRUST BANCORP INC"),
    ("WAY", "Waystar Holding Corp."),
    ("WBTN", "WEBTOON Entertainment Inc."),
    ("WD", "Walker & Dunlop, Inc."),
    ("WDFC", "WD 40 CO"),
    ("WEAV", "Weave Communications, Inc."),
    ("WERN", "WERNER ENTERPRISES INC"),
    ("WEST", "Westrock Coffee Co"),
    ("WEYS", "WEYCO GROUP INC"),
    ("WGO", "WINNEBAGO INDUSTRIES INC"),
    ("WGS", "GeneDx Holdings Corp."),
    ("WHD", "Cactus, Inc."),
    ("WINA", "WINMARK CORP"),
    ("WK", "WORKIVA INC"),
    ("WKC", "WORLD KINECT CORP"),
    ("WLDN", "Willdan Group, Inc."),
    ("WLFC", "WILLIS LEASE FINANCE CORP"),
    ("WLLBW", "Chord Energy Corp"),
    ("WLY", "JOHN WILEY & SONS, INC."),
    ("WMK", "WEIS MARKETS INC"),
    ("WNC", "WABASH NATIONAL Corp"),
    ("WNS", "WNS (HOLDINGS) LTD"),
    ("WOOF", "Petco Health & Wellness Company, Inc."),
    ("WOR", "WORTHINGTON ENTERPRISES, INC."),
    ("WOW", "WideOpenWest, Inc."),
    ("WRBY", "Warby Parker Inc."),
    ("WRLD", "WORLD ACCEPTANCE CORP"),
    ("WS", "Worthington Steel, Inc."),
    ("WSBC", "WESBANCO INC"),
    ("WSBF", "Waterstone Financial, Inc."),
    ("WSFS", "WSFS FINANCIAL CORP"),
    ("WSR", "Whitestone REIT"),
    ("WT", "WisdomTree, Inc."),
    ("WTBA", "WEST BANCORPORATION INC"),
    ("WTI", "W&T OFFSHORE INC"),
    ("WTS", "WATTS WATER TECHNOLOGIES INC"),
    ("WTTR", "Select Water Solutions, Inc."),
    ("WULF", "TERAWULF INC."),
    ("WVE", "Wave Life Sciences Ltd."),
    ("WWW", "WOLVERINE WORLD WIDE INC /DE/"),
    ("XBIT", "XBiotech Inc."),
    ("XERS", "Xeris Biopharma Holdings, Inc."),
    ("XFOR", "X4 Pharmaceuticals, Inc"),
    ("XHR", "Xenia Hotels & Resorts, Inc."),
    ("XMTR", "Xometry, Inc."),
    ("XNCR", "Xencor Inc"),
    ("XOMA", "XOMA Royalty Corp"),
    ("XPEL", "XPEL, Inc."),
    ("XPER", "Xperi Inc."),
    ("XPOF", "Xponential Fitness, Inc."),
    ("XPRO", "EXPRO GROUP HOLDINGS N.V."),
    ("XRX", "Xerox Holdings Corp"),
    ("YELP", "YELP INC"),
    ("YEXT", "Yext, Inc."),
    ("YMAB", "Y-mAbs Therapeutics, Inc."),
    ("YORW", "YORK WATER CO"),
    ("YOU", "Clear Secure, Inc."),
    ("ZBIO", "Zenas BioPharma, Inc."),
    ("ZD", "ZIFF DAVIS, INC."),
    ("ZETA", "Zeta Global Holdings Corp."),
    ("ZEUS", "OLYMPIC STEEL INC"),
    ("ZIMV", "ZimVie Inc."),
    ("ZIP", "ZIPRECRUITER, INC."),
    ("ZNTL", "Zentalis Pharmaceuticals, Inc."),
    ("ZSPC", "Zspace Inc."),
    ("ZUMZ", "Zumiez Inc"),
    ("ZURA", "Zura Bio Ltd"),
    ("ZVRA", "ZEVRA THERAPEUTICS, INC."),
    ("ZWS", "Zurn Elkay Water Solutions Corp"),
    ("ZYME", "Zymeworks Inc."),
    ("ZYXI", "ZYNEX INC"),
]